from pydantic import BaseModel, Field
from typing import List, Optional, Dict
from datetime import datetime # ADD THIS
import json

class ContentGenerationError(Exception):
    """Custom exception for failures during the content generation process."""
    pass

class ImageDetails(BaseModel):
    """
    A structured representation of all metadata for a single image, whether
    it's AI-generated or a stock photo.
    """
    source: str
    query: str
    alt_text: str
    caption: str
    description: str
    public_url: Optional[str] = None # NEW: To store the final GCS URL

class ImagePathDetails(BaseModel):
    """Holds the local path of a generated image and its desired final filename for upload."""
    local_path: str
    upload_filename: str

class QAReview(BaseModel):
    """Holds the results of the QA review."""
    approved: bool
    rejection_reason: str = ""

class BlogPost(BaseModel):
    """
    The central data model that represents a single blog post as it moves
    through the entire creation pipeline. It accumulates data from each agent.
    """
    # --- Data from Google Sheets 'Content Plan' ---
    topic: str
    primary_keyword: str
    secondary_keywords: List[str] = Field(default_factory=list)
    target_audience: str
    category: str
    internal_links: List[str] = Field(default_factory=list)
    sheet_row_index: int
    status: str = "Pending"
    slug: str = "" # NEW: For URL generation
    refinement_loops: int = 2
    timestamp: str = Field(default_factory=lambda: datetime.now().isoformat()) # ADD THIS

    # --- Data for internal linking ---
    published_posts_map: Dict[str, str] = Field(default_factory=dict) # New: Map of published posts

    # --- Data generated by the CreativeAgent ---
    generated_title: str = ""
    raw_content: str = ""
    tags: List[str] = Field(default_factory=list)
    images: List[ImageDetails] = Field(default_factory=list)
    image_path_details: List[ImagePathDetails] = Field(default_factory=list)

    meta_description: str = ""
    related_keywords: List[str] = Field(default_factory=list)
    social_media_posts: Dict[str, str] = Field(default_factory=dict)

    # --- Processed data for publishing ---
    edited_content: str = ""
    strapi_post_id: Optional[int] = None
    strapi_url: str = ""
    log_sheet_row_index: Optional[int] = None
    qa_review: Optional[QAReview] = None

class StrapiPost(BaseModel):
    """
    Pydantic model representing the structure of a Post in Strapi.
    This ensures type safety and validation when interacting with the Strapi API.
    """
    title: str = Field(..., alias="Title")
    slug: str = Field(..., alias="Slug")
    body_content: List[dict] = Field(..., alias="BodyContent")
    post_status: str = Field(default="draft", alias="PostStatus")
    keywords: Optional[str] = Field(default=None, alias="Keywords")
    meta_description: Optional[str] = Field(default=None, alias="MetaDescription")
    featured_image: Optional[int] = Field(default=None, alias="FeaturedImage")
    image_alt_text: Optional[str] = Field(default=None, alias="ImageAltText")
    author: Optional[str] = Field(default=None, alias="Author")

    class Config:
        """
        Pydantic config to allow population by alias.
        This lets us use Python-friendly snake_case variable names
        that map to Strapi's PascalCase field names.
        """
        allow_population_by_field_name = False
        populate_by_name = True
