apiVersion: 1

datasources:
  - name: Local Brain DB
    uid: local-brain-db
    type: postgres
    access: proxy
    url: postgres-local:5432
    database: gladlabs_brain
    user: gladlabs
    secureJsonData:
      password: gladlabs-brain-local
    jsonData:
      sslmode: disable
      postgresVersion: 1600
    isDefault: true
    editable: true
