"""
Unit tests for utils.startup_manager module.

Covers:
- StartupManager.__init__: default attribute state
- _validate_secrets(): production/dev behaviour, violations, empty env vars
- _initialize_database(): success, failure (raises SystemExit)
- _run_migrations(): success (ok=True), success (ok=False), Exception, content store failure
- _setup_redis_cache(): enabled, disabled, Exception
- _verify_connections(): healthy, unhealthy status, Exception
- _log_startup_summary(): smoke test (no crash)
- shutdown(): redis, DB, Exception
- initialize_all_services(): success path, Exception path, SystemExit re-raise

Task dispatch lives in Prefect (Glad-Labs/poindexter#410); the legacy
in-process TaskExecutor was deleted in Stage 4 (2026-05-16), so the
``_initialize_task_executor`` lifecycle hook is gone and the shutdown
path no longer stops an executor.

All tests are pure — zero DB, LLM, or network calls.
"""

import asyncio
import os
import sys
from types import SimpleNamespace
from typing import Any
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from poindexter.services.site_config import SiteConfig
from tests.unit._nonempty import nonempty

# ---------------------------------------------------------------------------
# Helper: build a StartupManager with sys.modules pre-populated so imports
# inside the lazy methods are intercepted.
# ---------------------------------------------------------------------------


def _make_manager():
    """Import StartupManager with a clean import context."""
    # Remove cached module so re-import is fresh each test (avoids state leakage)
    sys.modules.pop("poindexter.utils.startup_manager", None)
    from poindexter.utils.startup_manager import StartupManager

    return StartupManager(site_config=SiteConfig())


def _run(coro):
    """Run a coroutine synchronously."""
    try:
        loop = asyncio.get_event_loop()
    except RuntimeError:
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
    return loop.run_until_complete(coro)


# ---------------------------------------------------------------------------
# __init__
# ---------------------------------------------------------------------------


@pytest.mark.unit
class TestInit:
    def test_all_attributes_none_by_default(self):
        mgr = _make_manager()
        assert mgr.database_service is None
        assert mgr.redis_cache is None
        assert mgr.startup_error is None

    def test_site_config_is_required(self):
        """The old ``None`` default let each step build its own env-fallback
        SiteConfig, which the settings load could never reach."""
        from poindexter.utils.startup_manager import StartupManager

        with pytest.raises(TypeError, match="site_config"):
            StartupManager(site_config=None)


# ---------------------------------------------------------------------------
# _validate_secrets
# ---------------------------------------------------------------------------


@pytest.mark.unit
class TestValidateSecrets:
    def test_no_violations_in_production_does_not_raise(self):
        """When all secrets differ from defaults, production passes."""
        mgr = _make_manager()
        env = {
            "ENVIRONMENT": "production",
            "JWT_SECRET_KEY": "strong-unique-key",
            "JWT_SECRET": "another-strong-key",
            "SECRET_KEY": "yet-another-key",
            "REVALIDATE_SECRET": "solid-revalidate-secret",
        }
        with patch.dict(os.environ, env, clear=False):
            mgr._validate_secrets()  # Must not raise

    def test_default_value_in_production_warns_not_raises(self):
        """Default secrets in production now warn (auto-generated by config) instead of crashing."""
        mgr = _make_manager()
        env = {
            "ENVIRONMENT": "production",
            "JWT_SECRET_KEY": "development-secret-key-change-in-production",
        }
        with patch.dict(os.environ, env, clear=False):
            mgr._validate_secrets()  # Must not raise — just warns

    def test_default_value_in_development_logs_warning_not_raises(self):
        mgr = _make_manager()
        env = {
            "ENVIRONMENT": "development",
            "JWT_SECRET_KEY": "development-secret-key-change-in-production",
        }
        with patch.dict(os.environ, env, clear=False):
            # Should not raise — just warn
            mgr._validate_secrets()

    def test_empty_env_var_does_not_trigger_violation(self):
        """Empty string means not set — only warn, don't block."""
        mgr = _make_manager()
        # Remove all secret keys and set to empty to ensure the 'if actual == default_value' branch
        # is NOT hit (empty string is handled differently — no violation appended)
        env = {
            "ENVIRONMENT": "production",
            "JWT_SECRET_KEY": "",
            "JWT_SECRET": "",
            "SECRET_KEY": "",
            "REVALIDATE_SECRET": "",
        }
        with patch.dict(os.environ, env, clear=False):
            # Empty strings are not treated as violations, so no error in production
            mgr._validate_secrets()

    def test_multiple_violations_in_production_warns_not_raises(self):
        """Multiple default secrets warn instead of raising."""
        mgr = _make_manager()
        env = {
            "ENVIRONMENT": "production",
            "JWT_SECRET_KEY": "development-secret-key-change-in-production",
            "SECRET_KEY": "your-secret-key-here",
        }
        with patch.dict(os.environ, env, clear=False):
            mgr._validate_secrets()  # Must not raise — just warns

    def test_staging_is_not_production(self):
        """staging environment should warn, not raise."""
        mgr = _make_manager()
        env = {
            "ENVIRONMENT": "staging",
            "JWT_SECRET_KEY": "development-secret-key-change-in-production",
        }
        with patch.dict(os.environ, env, clear=False):
            mgr._validate_secrets()  # Must not raise

    def test_default_environment_warns_on_default_secret(self):
        """ENVIRONMENT not set → defaults to 'production' → warns on default secret."""
        mgr = _make_manager()
        env = {"JWT_SECRET_KEY": "development-secret-key-change-in-production"}
        # Remove ENVIRONMENT so the default is used
        stripped = {k: v for k, v in os.environ.items() if k != "ENVIRONMENT"}
        stripped.update(env)
        with patch.dict(os.environ, stripped, clear=True):
            mgr._validate_secrets()  # Must not raise — just warns


# ---------------------------------------------------------------------------
# _initialize_database
# ---------------------------------------------------------------------------


@pytest.mark.unit
class TestInitializeDatabase:
    def test_success_sets_database_service(self):
        mgr = _make_manager()
        mock_db = AsyncMock()
        mock_db.pool = MagicMock()
        mock_db.tasks = MagicMock()
        mock_db.users = MagicMock()
        mock_db.content = MagicMock()
        mock_db_cls = MagicMock(return_value=mock_db)

        with patch.dict(
            "sys.modules", {"poindexter.services.database_service": MagicMock(DatabaseService=mock_db_cls)}
        ):
            _run(mgr._initialize_database())

        assert mgr.database_service is mock_db
        # A truthy pool starts the ConnectionPoolHealth monitor (an infinite
        # ``auto_health_check`` loop). Cancel it so it doesn't leak past the
        # event loop as "Task was destroyed but it is pending!"
        # (Glad-Labs/glad-labs-stack#997).
        _run(mgr._cancel_background_tasks())

    def test_failure_raises_system_exit(self, operator_pages):
        mgr = _make_manager()
        mock_db = AsyncMock()
        mock_db.initialize.side_effect = Exception("connection refused")
        mock_db_cls = MagicMock(return_value=mock_db)

        with patch.dict(
            "sys.modules", {"poindexter.services.database_service": MagicMock(DatabaseService=mock_db_cls)}
        ):
            with pytest.raises(SystemExit):
                _run(mgr._initialize_database())

        # This failure pages the operator (critical — Postgres is required).
        # Assert it through the unit-tier isolation stub
        # (tests.unit.conftest._isolate_operator_notifier) rather than a real
        # send — before that guard existed this appended a real line to
        # ~/.poindexter/alerts.log on every run (poindexter#1084 — 570 fake
        # CRITICAL entries traced to this test and its sibling below).
        assert any(
            "database connection failed" in p["text"] and "Severity: critical" in p["text"]
            for p in operator_pages
        ), f"expected a critical page naming the DB failure, got {operator_pages!r}"

    def test_failure_does_not_set_database_service(self, operator_pages):
        mgr = _make_manager()
        mock_db = AsyncMock()
        mock_db.initialize.side_effect = Exception("timeout")
        mock_db_cls = MagicMock(return_value=mock_db)

        with patch.dict(
            "sys.modules", {"poindexter.services.database_service": MagicMock(DatabaseService=mock_db_cls)}
        ):
            with pytest.raises(SystemExit):
                _run(mgr._initialize_database())

        # database_service was NOT assigned before exception
        # (the exception happens during initialize(), so the attribute IS set to the instance)
        # just verify SystemExit propagated — attribute state is moot
        assert any(
            "database connection failed" in p["text"] and "Severity: critical" in p["text"]
            for p in operator_pages
        ), f"expected a critical page naming the DB failure, got {operator_pages!r}"


# ---------------------------------------------------------------------------
# _run_migrations
# ---------------------------------------------------------------------------


@pytest.mark.unit
class TestRunMigrations:
    def _mock_db(self):
        db = MagicMock()
        db.pool = MagicMock()
        return db

    def test_migration_ok_true(self):
        mgr = _make_manager()
        mgr.database_service = self._mock_db()

        mock_migrations = MagicMock()
        mock_migrations.run_migrations = AsyncMock(return_value=True)
        mock_content = MagicMock()
        mock_content.get_content_task_store = MagicMock()

        with patch.dict(
            "sys.modules",
            {
                "poindexter.services.migrations": mock_migrations,
                "poindexter.services.content_router_service": mock_content,
            },
        ):
            _run(mgr._run_migrations())

        mock_migrations.run_migrations.assert_awaited_once()

    def test_migration_returns_false_skips_not_raises(self):
        """run_migrations returning False means no pool / skipped — not a failure.
        startup_manager must NOT exit in this case (#697)."""
        mgr = _make_manager()
        mgr.database_service = self._mock_db()

        mock_migrations = MagicMock()
        mock_migrations.run_migrations = AsyncMock(return_value=False)
        mock_content = MagicMock()
        mock_content.get_content_task_store = MagicMock()

        with patch.dict(
            "sys.modules",
            {
                "poindexter.services.migrations": mock_migrations,
                "poindexter.services.content_router_service": mock_content,
            },
        ):
            _run(mgr._run_migrations())  # False = skip, must not raise

    def test_migration_exception_raises_system_exit(self):
        """run_migrations raising means a migration failed — startup_manager must
        call notify_operator and raise SystemExit(1), same posture as a missing
        DB connection (#697)."""
        mgr = _make_manager()
        mgr.database_service = self._mock_db()

        mock_migrations = MagicMock()
        mock_migrations.run_migrations = AsyncMock(side_effect=RuntimeError("migration error"))
        mock_content = MagicMock()
        mock_content.get_content_task_store = MagicMock()

        with patch.dict(
            "sys.modules",
            {
                "poindexter.services.migrations": mock_migrations,
                "poindexter.services.content_router_service": mock_content,
                "poindexter.brain.operator_notifier": MagicMock(notify_operator=MagicMock()),
            },
        ):
            with pytest.raises(SystemExit):
                _run(mgr._run_migrations())

    def test_content_task_store_failure_warns_not_raises(self):
        mgr = _make_manager()
        mgr.database_service = self._mock_db()

        mock_migrations = MagicMock()
        mock_migrations.run_migrations = AsyncMock(return_value=True)
        mock_content = MagicMock()
        mock_content.get_content_task_store = MagicMock(side_effect=Exception("store fail"))

        with patch.dict(
            "sys.modules",
            {
                "poindexter.services.migrations": mock_migrations,
                "poindexter.services.content_router_service": mock_content,
            },
        ):
            _run(mgr._run_migrations())  # Must not raise

    def test_seed_all_defaults_called_after_migrations(self):
        """After successful migrations, the #379 seeder runs against the same pool."""
        mgr = _make_manager()
        mgr.database_service = self._mock_db()
        pool = mgr.database_service.pool

        mock_migrations = MagicMock()
        mock_migrations.run_migrations = AsyncMock(return_value=True)
        mock_content = MagicMock()
        mock_seeder = MagicMock()
        mock_seeder.seed_all_defaults = AsyncMock(return_value=42)

        with patch.dict(
            "sys.modules",
            {
                "poindexter.services.migrations": mock_migrations,
                "poindexter.services.content_router_service": mock_content,
                "poindexter.services.settings_defaults": mock_seeder,
            },
        ):
            _run(mgr._run_migrations())

        mock_seeder.seed_all_defaults.assert_awaited_once()
        # Seeder receives the database pool, not the wrapper service
        call_args = mock_seeder.seed_all_defaults.await_args
        assert call_args.args[0] is pool

    def test_local_site_identity_fill_runs_after_the_seed_and_the_overlay(self):
        """The fill only fills EMPTY identity, so it must run after the seed and
        the operator overlay: anything they write has to win."""
        mgr = _make_manager()
        mgr.database_service = self._mock_db()
        pool = mgr.database_service.pool
        order: list[str] = []

        def _step(name, result=0):
            async def _run_step(*_a, **_k):
                order.append(name)
                return result

            return AsyncMock(side_effect=_run_step)

        mock_migrations = MagicMock()
        mock_migrations.run_migrations = _step("migrations", True)
        mock_seeder = MagicMock()
        mock_seeder.seed_all_defaults = _step("seed")
        mock_seeder.apply_operator_overrides = _step("overlay")
        mock_seeder.seed_operator_subreddit_profiles = _step("subreddits")
        mock_local_site = MagicMock()
        mock_local_site.fill_local_site_identity = _step("identity_fill", {})

        with patch.dict(
            "sys.modules",
            {
                "poindexter.services.migrations": mock_migrations,
                "poindexter.services.content_router_service": MagicMock(),
                "poindexter.services.settings_defaults": mock_seeder,
                "poindexter.services.local_site": mock_local_site,
            },
        ):
            _run(mgr._run_migrations())

        assert order.index("seed") < order.index("overlay") < order.index("identity_fill")
        assert mock_local_site.fill_local_site_identity.await_args.args[0] is pool

    def test_local_site_identity_fill_failure_does_not_abort_startup(self):
        mgr = _make_manager()
        mgr.database_service = self._mock_db()
        mock_migrations = MagicMock()
        mock_migrations.run_migrations = AsyncMock(return_value=True)
        mock_seeder = MagicMock()
        mock_seeder.seed_all_defaults = AsyncMock(return_value=0)
        mock_local_site = MagicMock()
        mock_local_site.fill_local_site_identity = AsyncMock(side_effect=Exception("db gone"))

        with patch.dict(
            "sys.modules",
            {
                "poindexter.services.migrations": mock_migrations,
                "poindexter.services.content_router_service": MagicMock(),
                "poindexter.services.settings_defaults": mock_seeder,
                "poindexter.services.local_site": mock_local_site,
            },
        ):
            _run(mgr._run_migrations())

        mock_local_site.fill_local_site_identity.assert_awaited_once()

    def test_seed_failure_does_not_abort_startup(self):
        """seed_all_defaults() raising is logged but doesn't propagate (lazy default fallback)."""
        mgr = _make_manager()
        mgr.database_service = self._mock_db()

        mock_migrations = MagicMock()
        mock_migrations.run_migrations = AsyncMock(return_value=True)
        mock_content = MagicMock()
        mock_seeder = MagicMock()
        mock_seeder.seed_all_defaults = AsyncMock(side_effect=Exception("seed exploded"))

        with patch.dict(
            "sys.modules",
            {
                "poindexter.services.migrations": mock_migrations,
                "poindexter.services.content_router_service": mock_content,
                "poindexter.services.settings_defaults": mock_seeder,
            },
        ):
            _run(mgr._run_migrations())  # Must not raise

    def test_seed_skipped_when_no_pool(self):
        """When the DB pool is None, the seeder import path is short-circuited."""
        mgr = _make_manager()
        mgr.database_service = MagicMock()
        mgr.database_service.pool = None  # simulate degraded startup

        mock_migrations = MagicMock()
        mock_migrations.run_migrations = AsyncMock(return_value=True)
        mock_content = MagicMock()
        mock_seeder = MagicMock()
        mock_seeder.seed_all_defaults = AsyncMock(return_value=0)

        with patch.dict(
            "sys.modules",
            {
                "poindexter.services.migrations": mock_migrations,
                "poindexter.services.content_router_service": mock_content,
                "poindexter.services.settings_defaults": mock_seeder,
            },
        ):
            _run(mgr._run_migrations())

        # No pool — seeder should not be invoked at all
        mock_seeder.seed_all_defaults.assert_not_awaited()


# ---------------------------------------------------------------------------
# _ensure_active_graph_defs_stamped — boot-time graph_def self-heal (#755)
# ---------------------------------------------------------------------------


@pytest.mark.unit
class TestEnsureActiveGraphDefsStamped:
    """The boot step delegates to ``pipeline_architect.ensure_active_graph_defs_stamped``
    with the live pool, no-ops without a pool, and never aborts startup —
    matching the best-effort posture of the seeder / model-validator steps."""

    def _mock_db(self):
        db = MagicMock()
        db.pool = MagicMock()
        return db

    def test_delegates_to_pipeline_architect_with_pool(self):
        mgr = _make_manager()
        mgr.database_service = self._mock_db()
        pool = mgr.database_service.pool

        mock_pa = MagicMock()
        mock_pa.ensure_active_graph_defs_stamped = AsyncMock(return_value=2)

        with patch.dict("sys.modules", {"poindexter.services.pipeline_architect": mock_pa}):
            _run(mgr._ensure_active_graph_defs_stamped())

        mock_pa.ensure_active_graph_defs_stamped.assert_awaited_once()
        # Receives the DB pool, not the wrapper service.
        assert mock_pa.ensure_active_graph_defs_stamped.await_args.args[0] is pool

    def test_skips_when_pool_is_none(self):
        mgr = _make_manager()
        mgr.database_service = MagicMock()
        mgr.database_service.pool = None  # degraded startup

        mock_pa = MagicMock()
        mock_pa.ensure_active_graph_defs_stamped = AsyncMock()

        with patch.dict("sys.modules", {"poindexter.services.pipeline_architect": mock_pa}):
            _run(mgr._ensure_active_graph_defs_stamped())

        mock_pa.ensure_active_graph_defs_stamped.assert_not_awaited()

    def test_skips_when_no_database_service(self):
        mgr = _make_manager()
        mgr.database_service = None
        _run(mgr._ensure_active_graph_defs_stamped())  # Must not raise

    def test_exception_swallowed_not_raised(self):
        """A failure in the stamping step must NOT abort startup (best-effort)."""
        mgr = _make_manager()
        mgr.database_service = self._mock_db()

        mock_pa = MagicMock()
        mock_pa.ensure_active_graph_defs_stamped = AsyncMock(
            side_effect=RuntimeError("registry exploded")
        )

        with patch.dict("sys.modules", {"poindexter.services.pipeline_architect": mock_pa}):
            _run(mgr._ensure_active_graph_defs_stamped())  # Must not raise

    def test_import_unavailable_no_op(self):
        """If pipeline_architect can't be imported (minimal deploy), no-op."""
        mgr = _make_manager()
        mgr.database_service = self._mock_db()

        # A None sys.modules entry makes ``from services.pipeline_architect
        # import ...`` raise ImportError — the import-guard must swallow it.
        with patch.dict("sys.modules", {"poindexter.services.pipeline_architect": None}):
            _run(mgr._ensure_active_graph_defs_stamped())  # Must not raise


# ---------------------------------------------------------------------------
# _setup_redis_cache
# ---------------------------------------------------------------------------


@pytest.mark.unit
class TestSetupRedisCache:
    def test_redis_enabled_sets_cache(self):
        mgr = _make_manager()
        mock_cache = MagicMock()
        mock_cache._enabled = True
        mock_redis_cls = MagicMock()
        mock_redis_cls.create = AsyncMock(return_value=mock_cache)
        mock_module = MagicMock(RedisCache=mock_redis_cls)

        with patch.dict("sys.modules", {"poindexter.services.redis_cache": mock_module}):
            _run(mgr._setup_redis_cache())

        assert mgr.redis_cache is mock_cache

    def test_redis_disabled_sets_cache_anyway(self):
        mgr = _make_manager()
        mock_cache = MagicMock()
        mock_cache._enabled = False
        mock_redis_cls = MagicMock()
        mock_redis_cls.create = AsyncMock(return_value=mock_cache)
        mock_module = MagicMock(RedisCache=mock_redis_cls)

        with patch.dict("sys.modules", {"poindexter.services.redis_cache": mock_module}):
            _run(mgr._setup_redis_cache())

        assert mgr.redis_cache is mock_cache

    def test_redis_exception_warns_not_raises(self):
        mgr = _make_manager()
        mock_redis_cls = MagicMock()
        mock_redis_cls.create = AsyncMock(side_effect=Exception("connection refused"))
        mock_module = MagicMock(RedisCache=mock_redis_cls)

        with patch.dict("sys.modules", {"poindexter.services.redis_cache": mock_module}):
            _run(mgr._setup_redis_cache())  # Must not raise

        assert mgr.redis_cache is None


# ---------------------------------------------------------------------------
# _initialize_task_executor — deleted in Glad-Labs/poindexter#410 Stage 4
# (2026-05-16). Prefect owns dispatch; nothing to construct in-process.
# ---------------------------------------------------------------------------


# ---------------------------------------------------------------------------
# _verify_connections
# ---------------------------------------------------------------------------


@pytest.mark.unit
class TestVerifyConnections:
    def test_healthy_database_logs_pass(self):
        mgr = _make_manager()
        mock_db = AsyncMock()
        mock_db.health_check = AsyncMock(return_value={"status": "healthy"})
        mgr.database_service = mock_db

        _run(mgr._verify_connections())

        mock_db.health_check.assert_awaited_once()

    def test_unhealthy_status_logs_warning(self):
        mgr = _make_manager()
        mock_db = AsyncMock()
        mock_db.health_check = AsyncMock(return_value={"status": "degraded"})
        mgr.database_service = mock_db

        _run(mgr._verify_connections())  # Must not raise

    def test_exception_logs_warning_not_raises(self):
        mgr = _make_manager()
        mock_db = AsyncMock()
        mock_db.health_check = AsyncMock(side_effect=Exception("health check failed"))
        mgr.database_service = mock_db

        _run(mgr._verify_connections())  # Must not raise

    def test_no_database_service_skips_check(self):
        mgr = _make_manager()
        mgr.database_service = None

        _run(mgr._verify_connections())  # Must not raise — no DB to check


# ---------------------------------------------------------------------------
# _log_startup_summary
# ---------------------------------------------------------------------------


@pytest.mark.unit
class TestLogStartupSummary:
    def test_smoke_all_none(self):
        mgr = _make_manager()
        mgr._log_startup_summary()  # Must not raise even when all services are None

    def test_smoke_with_services(self):
        mgr = _make_manager()
        mgr.database_service = MagicMock()
        mgr.redis_cache = MagicMock()
        mgr.redis_cache._enabled = True
        mgr._log_startup_summary()  # Must not raise


# ---------------------------------------------------------------------------
# shutdown
# ---------------------------------------------------------------------------


@pytest.mark.unit
class TestShutdown:
    """Shutdown sequence — Redis + DB only.

    Task dispatch lives in Prefect now (Glad-Labs/poindexter#410); the
    legacy ``self.task_executor.stop()`` call was removed in Stage 4
    (2026-05-16) alongside the deletion of ``services/task_executor.py``.
    """

    def test_shutdown_closes_redis(self):
        mgr = _make_manager()
        mock_redis = AsyncMock()
        mock_redis.close = AsyncMock()
        mgr.redis_cache = mock_redis

        _run(mgr.shutdown())

        mock_redis.close.assert_awaited_once()

    def test_shutdown_closes_database(self):
        mgr = _make_manager()
        mock_db = AsyncMock()
        mock_db.close = AsyncMock()
        mgr.database_service = mock_db

        _run(mgr.shutdown())

        mock_db.close.assert_awaited_once()

    def test_shutdown_no_services_no_crash(self):
        mgr = _make_manager()
        _run(mgr.shutdown())  # Must not raise when nothing is set

    def test_shutdown_cancels_background_tasks(self):
        """The pool-health monitor (and any other long-running background
        task) must be cancelled on shutdown — a pending ``auto_health_check``
        loop that outlives the event loop is the leak fixed in
        Glad-Labs/glad-labs-stack#997.
        """

        async def _scenario():
            mgr = _make_manager()

            # Stand in for the ConnectionPoolHealth monitor: an infinite loop
            # registered exactly the way ``_initialize_database`` registers it.
            async def _never_ending():
                while True:
                    await asyncio.sleep(3600)

            task = asyncio.create_task(_never_ending())
            mgr._background_tasks.add(task)
            task.add_done_callback(mgr._background_tasks.discard)

            # Let the task actually start its loop before we tear down.
            await asyncio.sleep(0)

            await mgr.shutdown()

            assert task.cancelled()
            assert len(mgr._background_tasks) == 0

        _run(_scenario())


# ---------------------------------------------------------------------------
# initialize_all_services
# ---------------------------------------------------------------------------


@pytest.mark.unit
class TestInitializeAllServices:
    def _stub_all(self, mgr):
        """Stub all individual init methods so they succeed instantly."""
        mgr._validate_secrets = MagicMock()
        mgr._initialize_database = AsyncMock()
        mgr._run_migrations = AsyncMock()
        mgr._setup_redis_cache = AsyncMock()
        mgr._verify_connections = AsyncMock()
        mgr._log_startup_summary = MagicMock()

    def test_success_returns_dict_with_expected_keys(self):
        mgr = _make_manager()
        self._stub_all(mgr)

        result = _run(mgr.initialize_all_services())

        assert isinstance(result, dict)
        expected_keys = {
            "database",
            "redis_cache",
            "startup_error",
        }
        assert set(result.keys()) == expected_keys

    def test_success_startup_error_is_none(self):
        mgr = _make_manager()
        self._stub_all(mgr)

        result = _run(mgr.initialize_all_services())

        assert result["startup_error"] is None

    def test_exception_during_step_sets_startup_error_and_raises(self):
        mgr = _make_manager()
        self._stub_all(mgr)
        mgr._initialize_database = AsyncMock(side_effect=RuntimeError("DB failed"))

        with pytest.raises(RuntimeError, match="DB failed"):
            _run(mgr.initialize_all_services())

    def test_system_exit_re_raised(self):
        mgr = _make_manager()
        self._stub_all(mgr)
        mgr._initialize_database = AsyncMock(side_effect=SystemExit(1))

        with pytest.raises(SystemExit):
            _run(mgr.initialize_all_services())

    def test_exception_sets_startup_error_attribute(self):
        mgr = _make_manager()
        self._stub_all(mgr)
        mgr._run_migrations = AsyncMock(side_effect=RuntimeError("migration crashed"))

        with pytest.raises(RuntimeError):
            _run(mgr.initialize_all_services())

        assert mgr.startup_error is not None
        assert "Critical startup failure" in mgr.startup_error

    def test_log_startup_summary_called_on_success(self):
        mgr = _make_manager()
        self._stub_all(mgr)

        _run(mgr.initialize_all_services())

        mgr._log_startup_summary.assert_called_once()

    def test_all_steps_called_in_order(self):
        mgr = _make_manager()
        call_order = []

        mgr._validate_secrets = MagicMock(side_effect=lambda: call_order.append("validate"))
        mgr._initialize_database = AsyncMock(side_effect=lambda: call_order.append("db"))
        mgr._run_migrations = AsyncMock(side_effect=lambda: call_order.append("migrations"))
        mgr._load_site_config = AsyncMock(side_effect=lambda: call_order.append("load_settings"))
        mgr._setup_redis_cache = AsyncMock(side_effect=lambda: call_order.append("redis"))
        mgr._verify_connections = AsyncMock(side_effect=lambda: call_order.append("verify"))
        mgr._log_startup_summary = MagicMock()

        _run(mgr.initialize_all_services())

        # The settings load sits between migrations (which write app_settings)
        # and the first step that reads a setting (Redis).
        assert call_order == [
            "validate",
            "db",
            "migrations",
            "load_settings",
            "redis",
            "verify",
        ]

    def test_graph_def_stamp_runs_after_migrations(self):
        """The #755 graph_def self-heal must run AFTER migrations (the reseed
        that un-stamps the row is a migration) and BEFORE the rest of boot."""
        mgr = _make_manager()
        call_order = []

        mgr._validate_secrets = MagicMock()
        mgr._initialize_database = AsyncMock()
        mgr._run_migrations = AsyncMock(side_effect=lambda: call_order.append("migrations"))
        mgr._ensure_active_graph_defs_stamped = AsyncMock(
            side_effect=lambda: call_order.append("graphdef_stamp")
        )
        mgr._setup_redis_cache = AsyncMock(side_effect=lambda: call_order.append("redis"))
        mgr._verify_connections = AsyncMock()
        mgr._log_startup_summary = MagicMock()

        _run(mgr.initialize_all_services())

        assert "graphdef_stamp" in call_order
        assert call_order.index("migrations") < call_order.index("graphdef_stamp")
        assert call_order.index("graphdef_stamp") < call_order.index("redis")


# ---------------------------------------------------------------------------
# Boot seam — every startup step reads app_settings, not env vars + defaults
# ---------------------------------------------------------------------------


class _RecordingSiteConfig(SiteConfig):
    """A real SiteConfig that notes, for each read, whether ``load()`` had run."""

    def __init__(self) -> None:
        super().__init__()
        self.reads: list[tuple[str, bool]] = []

    def get(self, key: str, default: str = "") -> str:
        self.reads.append((key, self.is_loaded))
        return super().get(key, default)

    def require(self, key: str) -> str:
        self.reads.append((key, self.is_loaded))
        return super().require(key)

    async def get_secret(self, key: str, default: str = "") -> str:
        self.reads.append((key, self.is_loaded))
        return await super().get_secret(key, default)


class _FakeConn:
    """An acquired connection, answering the queries boot sends through one."""

    def __init__(self, settings: dict[str, str]) -> None:
        self._settings = settings

    async def fetch(self, sql: str, *args: Any) -> list[dict[str, str]]:
        # The model validator's query: every non-empty ``*_model`` row.
        return [
            {"key": key, "value": value}
            for key, value in sorted(self._settings.items())
            if key.endswith("_model") and value
        ]

    async def fetchrow(self, sql: str, *args: Any) -> None:
        return None  # plugins.secrets.get_secret: this table holds no secrets


class _Acquire:
    def __init__(self, conn: _FakeConn) -> None:
        self._conn = conn

    async def __aenter__(self) -> _FakeConn:
        return self._conn

    async def __aexit__(self, *exc: Any) -> bool:
        return False


class _FakePool:
    """An asyncpg pool over one in-memory ``app_settings`` table."""

    def __init__(self, settings: dict[str, str]) -> None:
        self._settings = settings

    async def fetch(self, sql: str, *args: Any) -> list[dict[str, Any]]:
        # SiteConfig.load: every non-secret row.
        return [
            {"key": key, "value": value, "deprecated": False, "superseded_by": None}
            for key, value in self._settings.items()
        ]

    def acquire(self) -> _Acquire:
        return _Acquire(_FakeConn(self._settings))


class _FakeDatabaseService:
    def __init__(self, pool: _FakePool) -> None:
        self.pool = pool

    async def initialize(self) -> None:
        return None

    async def health_check(self) -> dict[str, str]:
        return {"status": "healthy"}

    async def close(self) -> None:
        return None


class _FakePoolHealth:
    def __init__(self, pool: Any) -> None:
        self.pool = pool

    async def auto_health_check(self) -> None:
        return None


class _FakeOllama:
    """Stands in for the shared httpx client and records where requests went."""

    def __init__(self, installed: list[str]) -> None:
        self.urls: list[str] = []
        self._installed = installed

    async def get(self, url: str, **kwargs: Any) -> MagicMock:
        self.urls.append(url)
        resp = MagicMock()
        resp.json.return_value = {"models": [{"name": name} for name in self._installed]}
        return resp

    async def post(self, url: str, **kwargs: Any) -> MagicMock:
        self.urls.append(url)
        resp = MagicMock()
        resp.json.return_value = {"template": "<|im_start|>user\n{{ .Prompt }}"}
        return resp


# The stored values boot reads. None of them is what an env var or a code
# default would supply, so a step that acts on one can only have read it from
# app_settings.
_DB_SETTINGS = {
    "ollama_base_url": "http://ollama-from-db:11434",
    "ollama_model_validation_skip_keys": "sidecar_weights_model",
    "redis_enabled": "false",
    "retention_janitor_interval_hours": "12",
    "pipeline_writer_model": "ollama/writer:latest",
    # Not an Ollama model; only the stored skip list above says so.
    "sidecar_weights_model": "sidecar-weights-v2",
}


async def _boot(monkeypatch, settings: dict[str, str], notify: AsyncMock | None = None):
    """Run the real ``initialize_all_services()`` against ``settings``.

    Only the boundaries are faked: the asyncpg pool, the migration runner and
    seeders, Redis's client and Ollama's HTTP API. Every step that reads a
    setting runs for real. Two steps that read none are stubbed: the syntax
    scan (it compiles the whole ``modules/`` tree) and the graph_def self-heal
    (it imports the pipeline stack). The caller cancels the background tasks.
    """
    import poindexter.plugins.registry as registry
    import poindexter.services.database_service as database_service
    import poindexter.services.jwt_blocklist_service as jwt_blocklist_service
    import poindexter.services.migrations as migrations
    import poindexter.services.redis_cache as redis_cache
    import poindexter.services.settings_defaults as settings_defaults
    import poindexter.utils.connection_health as connection_health
    from poindexter.services.integrations import operator_notify, shared_context
    from poindexter.utils.startup_manager import StartupManager

    pool = _FakePool(dict(settings))
    fake_db = _FakeDatabaseService(pool)
    monkeypatch.setattr(database_service, "DatabaseService", lambda **kwargs: fake_db)
    monkeypatch.setattr(connection_health, "ConnectionPoolHealth", _FakePoolHealth)
    monkeypatch.setattr(migrations, "run_migrations", AsyncMock(return_value=True))
    for seeder in ("seed_all_defaults", "apply_operator_overrides", "seed_operator_subreddit_profiles"):
        monkeypatch.setattr(settings_defaults, seeder, AsyncMock(return_value=0))
    monkeypatch.setattr(registry, "get_modules", lambda: [])
    monkeypatch.setattr(
        jwt_blocklist_service,
        "jwt_blocklist",
        MagicMock(initialize=AsyncMock(), cleanup=AsyncMock()),
    )
    from_url = AsyncMock(side_effect=ConnectionError("no Redis in unit tests"))
    monkeypatch.setattr(redis_cache, "aioredis", MagicMock(from_url=from_url))
    ollama = _FakeOllama(installed=["writer:latest"])
    monkeypatch.setattr(operator_notify, "http_client", ollama)
    notify = notify or AsyncMock()
    monkeypatch.setattr(operator_notify, "notify_operator", notify)
    # Startup publishes the DB service and SiteConfig for notify_operator;
    # setattr restores whatever was there before this test.
    monkeypatch.setattr(shared_context, "_db_service", shared_context._db_service)
    monkeypatch.setattr(shared_context, "_site_config", shared_context._site_config)

    sc = _RecordingSiteConfig()
    mgr = StartupManager(site_config=sc)
    mgr._check_module_syntax = MagicMock()
    mgr._ensure_active_graph_defs_stamped = AsyncMock()

    await mgr.initialize_all_services()
    await asyncio.sleep(0)  # let the retention janitor's first cycle run

    return SimpleNamespace(mgr=mgr, sc=sc, fake_db=fake_db, ollama=ollama, notify=notify, from_url=from_url)


@pytest.fixture
async def booted(monkeypatch):
    boot = await _boot(monkeypatch, _DB_SETTINGS)
    yield boot
    await boot.mgr._cancel_background_tasks()


@pytest.mark.unit
class TestBootReadsStoredSettings:
    """The ordering bug verified on prod 2026-09-28.

    ``main.py`` loaded the SiteConfig only after ``initialize_all_services()``
    returned, so every setting read during startup resolved from env vars and
    code defaults. ``SiteConfig.get`` still stamped ``last_read_at``, so the
    keys looked live while their stored values did nothing: prod's
    ``enable_image_gen_warmup='true'`` never ran the warmup, and the Ollama
    model validator could not see ``ollama_model_validation_skip_keys``, the
    remedy its own comment prescribes for a false MISSING line.
    """

    async def test_no_step_reads_a_setting_before_the_load(self, booted):
        reads = list(nonempty(booted.sc.reads, "settings read during startup"))
        early = sorted({key for key, loaded in reads if not loaded})
        assert early == [], f"read before app_settings was loaded: {early}"

    async def test_every_setting_reading_step_ran(self, booted):
        """Guards the test above against passing because a step stopped
        running: each of these keys is read by a different step."""
        read = {key for key, _ in booted.sc.reads}
        assert {
            "redis_url",
            "redis_enabled",
            "ollama_base_url",
            "ollama_model_validation_skip_keys",
            "retention_janitor_interval_hours",
        } <= read

    async def test_validator_uses_the_stored_base_url(self, booted):
        assert booted.ollama.urls[0] == "http://ollama-from-db:11434/api/tags"

    async def test_validator_honours_the_stored_skip_list(self, booted):
        """``sidecar_weights_model`` is missing from Ollama, and only the
        stored skip list exempts it. Read pre-load, the list was empty and
        the key was reported MISSING on every boot."""
        booted.notify.assert_not_called()

    async def test_redis_honours_the_stored_switch(self, booted):
        """Prod stores ``redis_enabled=false``. Read pre-load it defaulted to
        true, and every boot tried ``redis://localhost:6379/0``."""
        booted.from_url.assert_not_called()
        assert booted.mgr.redis_cache._enabled is False

    async def test_a_startup_alert_reaches_a_wired_notifier(self, monkeypatch):
        """``notify_operator`` resolves the DB service and SiteConfig through
        ``shared_context``. main.py registered them only after startup
        returned, so the validator's alert found neither and was dropped at
        DEBUG on every boot."""
        from poindexter.services.integrations import shared_context

        seen: dict[str, Any] = {}

        async def _capture(message: str, **kwargs: Any) -> None:
            seen["db"] = shared_context.get_database_service()
            seen["site_config"] = shared_context.get_site_config()

        settings = {**_DB_SETTINGS, "voice_llm_model": "ollama/not-installed:latest"}
        boot = await _boot(monkeypatch, settings, notify=AsyncMock(side_effect=_capture))
        try:
            boot.notify.assert_called_once()
            assert "not-installed:latest" in boot.notify.call_args.args[0]
            assert seen["db"] is boot.fake_db
            assert seen["site_config"] is boot.sc
        finally:
            await boot.mgr._cancel_background_tasks()

    async def test_shutdown_cancels_the_retention_janitor(self, booted):
        janitor = [t for t in booted.mgr._background_tasks if t.get_name() == "retention_janitor"]
        assert len(janitor) == 1

        await booted.mgr.shutdown()

        assert janitor[0].cancelled()


@pytest.mark.unit
class TestLoadSiteConfig:
    async def test_loads_the_injected_instance_from_the_pool(self):
        from poindexter.utils.startup_manager import StartupManager

        sc = SiteConfig()
        mgr = StartupManager(site_config=sc)
        mgr.database_service = _FakeDatabaseService(_FakePool({"site_name": "Stored Name"}))

        await mgr._load_site_config()

        assert sc.is_loaded
        assert sc.get("site_name") == "Stored Name"

    async def test_no_pool_keeps_the_env_fallbacks(self):
        from poindexter.utils.startup_manager import StartupManager

        sc = SiteConfig()
        mgr = StartupManager(site_config=sc)

        await mgr._load_site_config()  # no database_service: must not raise

        assert not sc.is_loaded


@pytest.mark.unit
class TestPublishIntegrationsContext:
    def test_publishes_the_db_service_and_site_config(self, monkeypatch):
        from poindexter.services.integrations import shared_context
        from poindexter.utils.startup_manager import StartupManager

        monkeypatch.setattr(shared_context, "_db_service", None)
        monkeypatch.setattr(shared_context, "_site_config", None)
        sc = SiteConfig()
        mgr = StartupManager(site_config=sc)
        mgr.database_service = _FakeDatabaseService(_FakePool({}))

        mgr._publish_integrations_context()

        assert shared_context.get_database_service() is mgr.database_service
        assert shared_context.get_site_config() is sc

    def test_publishes_nothing_without_a_pool(self, monkeypatch):
        from poindexter.services.integrations import shared_context
        from poindexter.utils.startup_manager import StartupManager

        monkeypatch.setattr(shared_context, "_db_service", None)
        monkeypatch.setattr(shared_context, "_site_config", None)
        mgr = StartupManager(site_config=SiteConfig())

        mgr._publish_integrations_context()

        assert shared_context.get_database_service() is None
        assert shared_context.get_site_config() is None
