"""
Unit tests for utils.startup_manager module.

Covers:
- StartupManager.__init__: default attribute state
- _validate_secrets(): production/dev behaviour, violations, empty env vars
- _initialize_database(): success, failure (raises SystemExit)
- _run_migrations(): success (ok=True), success (ok=False), Exception, content store failure
- _setup_redis_cache(): enabled, disabled, Exception
- _verify_connections(): healthy, unhealthy status, Exception
- _log_startup_summary(): smoke test (no crash)
- shutdown(): redis, DB, Exception
- initialize_all_services(): success path, Exception path, SystemExit re-raise

Task dispatch lives in Prefect (Glad-Labs/poindexter#410); the legacy
in-process TaskExecutor was deleted in Stage 4 (2026-05-16), so the
``_initialize_task_executor`` lifecycle hook is gone and the shutdown
path no longer stops an executor.

All tests are pure — zero DB, LLM, or network calls.
"""

import asyncio
import os
import sys
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

# ---------------------------------------------------------------------------
# Helper: build a StartupManager with sys.modules pre-populated so imports
# inside the lazy methods are intercepted.
# ---------------------------------------------------------------------------


def _make_manager():
    """Import StartupManager with a clean import context."""
    # Remove cached module so re-import is fresh each test (avoids state leakage)
    sys.modules.pop("utils.startup_manager", None)
    from utils.startup_manager import StartupManager

    return StartupManager()


def _run(coro):
    """Run a coroutine synchronously."""
    try:
        loop = asyncio.get_event_loop()
    except RuntimeError:
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
    return loop.run_until_complete(coro)


# ---------------------------------------------------------------------------
# __init__
# ---------------------------------------------------------------------------


@pytest.mark.unit
class TestInit:
    def test_all_attributes_none_by_default(self):
        mgr = _make_manager()
        assert mgr.database_service is None
        assert mgr.redis_cache is None
        assert mgr.startup_error is None


# ---------------------------------------------------------------------------
# _validate_secrets
# ---------------------------------------------------------------------------


@pytest.mark.unit
class TestValidateSecrets:
    def test_no_violations_in_production_does_not_raise(self):
        """When all secrets differ from defaults, production passes."""
        mgr = _make_manager()
        env = {
            "ENVIRONMENT": "production",
            "JWT_SECRET_KEY": "strong-unique-key",
            "JWT_SECRET": "another-strong-key",
            "SECRET_KEY": "yet-another-key",
            "REVALIDATE_SECRET": "solid-revalidate-secret",
        }
        with patch.dict(os.environ, env, clear=False):
            mgr._validate_secrets()  # Must not raise

    def test_default_value_in_production_warns_not_raises(self):
        """Default secrets in production now warn (auto-generated by config) instead of crashing."""
        mgr = _make_manager()
        env = {
            "ENVIRONMENT": "production",
            "JWT_SECRET_KEY": "development-secret-key-change-in-production",
        }
        with patch.dict(os.environ, env, clear=False):
            mgr._validate_secrets()  # Must not raise — just warns

    def test_default_value_in_development_logs_warning_not_raises(self):
        mgr = _make_manager()
        env = {
            "ENVIRONMENT": "development",
            "JWT_SECRET_KEY": "development-secret-key-change-in-production",
        }
        with patch.dict(os.environ, env, clear=False):
            # Should not raise — just warn
            mgr._validate_secrets()

    def test_empty_env_var_does_not_trigger_violation(self):
        """Empty string means not set — only warn, don't block."""
        mgr = _make_manager()
        # Remove all secret keys and set to empty to ensure the 'if actual == default_value' branch
        # is NOT hit (empty string is handled differently — no violation appended)
        env = {
            "ENVIRONMENT": "production",
            "JWT_SECRET_KEY": "",
            "JWT_SECRET": "",
            "SECRET_KEY": "",
            "REVALIDATE_SECRET": "",
        }
        with patch.dict(os.environ, env, clear=False):
            # Empty strings are not treated as violations, so no error in production
            mgr._validate_secrets()

    def test_multiple_violations_in_production_warns_not_raises(self):
        """Multiple default secrets warn instead of raising."""
        mgr = _make_manager()
        env = {
            "ENVIRONMENT": "production",
            "JWT_SECRET_KEY": "development-secret-key-change-in-production",
            "SECRET_KEY": "your-secret-key-here",
        }
        with patch.dict(os.environ, env, clear=False):
            mgr._validate_secrets()  # Must not raise — just warns

    def test_staging_is_not_production(self):
        """staging environment should warn, not raise."""
        mgr = _make_manager()
        env = {
            "ENVIRONMENT": "staging",
            "JWT_SECRET_KEY": "development-secret-key-change-in-production",
        }
        with patch.dict(os.environ, env, clear=False):
            mgr._validate_secrets()  # Must not raise

    def test_default_environment_warns_on_default_secret(self):
        """ENVIRONMENT not set → defaults to 'production' → warns on default secret."""
        mgr = _make_manager()
        env = {"JWT_SECRET_KEY": "development-secret-key-change-in-production"}
        # Remove ENVIRONMENT so the default is used
        stripped = {k: v for k, v in os.environ.items() if k != "ENVIRONMENT"}
        stripped.update(env)
        with patch.dict(os.environ, stripped, clear=True):
            mgr._validate_secrets()  # Must not raise — just warns


# ---------------------------------------------------------------------------
# _initialize_database
# ---------------------------------------------------------------------------


@pytest.mark.unit
class TestInitializeDatabase:
    def test_success_sets_database_service(self):
        mgr = _make_manager()
        mock_db = AsyncMock()
        mock_db.pool = MagicMock()
        mock_db.tasks = MagicMock()
        mock_db.users = MagicMock()
        mock_db.content = MagicMock()
        mock_db_cls = MagicMock(return_value=mock_db)

        with patch.dict(
            "sys.modules", {"services.database_service": MagicMock(DatabaseService=mock_db_cls)}
        ):
            _run(mgr._initialize_database())

        assert mgr.database_service is mock_db

    def test_failure_raises_system_exit(self):
        mgr = _make_manager()
        mock_db = AsyncMock()
        mock_db.initialize.side_effect = Exception("connection refused")
        mock_db_cls = MagicMock(return_value=mock_db)

        with patch.dict(
            "sys.modules", {"services.database_service": MagicMock(DatabaseService=mock_db_cls)}
        ):
            with pytest.raises(SystemExit):
                _run(mgr._initialize_database())

    def test_failure_does_not_set_database_service(self):
        mgr = _make_manager()
        mock_db = AsyncMock()
        mock_db.initialize.side_effect = Exception("timeout")
        mock_db_cls = MagicMock(return_value=mock_db)

        with patch.dict(
            "sys.modules", {"services.database_service": MagicMock(DatabaseService=mock_db_cls)}
        ):
            with pytest.raises(SystemExit):
                _run(mgr._initialize_database())

        # database_service was NOT assigned before exception
        # (the exception happens during initialize(), so the attribute IS set to the instance)
        # just verify SystemExit propagated — attribute state is moot


# ---------------------------------------------------------------------------
# _run_migrations
# ---------------------------------------------------------------------------


@pytest.mark.unit
class TestRunMigrations:
    def _mock_db(self):
        db = MagicMock()
        db.pool = MagicMock()
        return db

    def test_migration_ok_true(self):
        mgr = _make_manager()
        mgr.database_service = self._mock_db()

        mock_migrations = MagicMock()
        mock_migrations.run_migrations = AsyncMock(return_value=True)
        mock_content = MagicMock()
        mock_content.get_content_task_store = MagicMock()

        with patch.dict(
            "sys.modules",
            {
                "services.migrations": mock_migrations,
                "services.content_router_service": mock_content,
            },
        ):
            _run(mgr._run_migrations())

        mock_migrations.run_migrations.assert_awaited_once()

    def test_migration_ok_false_warns_not_raises(self):
        mgr = _make_manager()
        mgr.database_service = self._mock_db()

        mock_migrations = MagicMock()
        mock_migrations.run_migrations = AsyncMock(return_value=False)
        mock_content = MagicMock()
        mock_content.get_content_task_store = MagicMock()

        with patch.dict(
            "sys.modules",
            {
                "services.migrations": mock_migrations,
                "services.content_router_service": mock_content,
            },
        ):
            _run(mgr._run_migrations())  # Must not raise

    def test_migration_exception_warns_not_raises(self):
        mgr = _make_manager()
        mgr.database_service = self._mock_db()

        mock_migrations = MagicMock()
        mock_migrations.run_migrations = AsyncMock(side_effect=Exception("migration error"))
        mock_content = MagicMock()
        mock_content.get_content_task_store = MagicMock()

        with patch.dict(
            "sys.modules",
            {
                "services.migrations": mock_migrations,
                "services.content_router_service": mock_content,
            },
        ):
            _run(mgr._run_migrations())  # Must not raise

    def test_content_task_store_failure_warns_not_raises(self):
        mgr = _make_manager()
        mgr.database_service = self._mock_db()

        mock_migrations = MagicMock()
        mock_migrations.run_migrations = AsyncMock(return_value=True)
        mock_content = MagicMock()
        mock_content.get_content_task_store = MagicMock(side_effect=Exception("store fail"))

        with patch.dict(
            "sys.modules",
            {
                "services.migrations": mock_migrations,
                "services.content_router_service": mock_content,
            },
        ):
            _run(mgr._run_migrations())  # Must not raise

    def test_seed_all_defaults_called_after_migrations(self):
        """After successful migrations, the #379 seeder runs against the same pool."""
        mgr = _make_manager()
        mgr.database_service = self._mock_db()
        pool = mgr.database_service.pool

        mock_migrations = MagicMock()
        mock_migrations.run_migrations = AsyncMock(return_value=True)
        mock_content = MagicMock()
        mock_seeder = MagicMock()
        mock_seeder.seed_all_defaults = AsyncMock(return_value=42)

        with patch.dict(
            "sys.modules",
            {
                "services.migrations": mock_migrations,
                "services.content_router_service": mock_content,
                "services.settings_defaults": mock_seeder,
            },
        ):
            _run(mgr._run_migrations())

        mock_seeder.seed_all_defaults.assert_awaited_once()
        # Seeder receives the database pool, not the wrapper service
        call_args = mock_seeder.seed_all_defaults.await_args
        assert call_args.args[0] is pool

    def test_seed_failure_does_not_abort_startup(self):
        """seed_all_defaults() raising is logged but doesn't propagate (lazy default fallback)."""
        mgr = _make_manager()
        mgr.database_service = self._mock_db()

        mock_migrations = MagicMock()
        mock_migrations.run_migrations = AsyncMock(return_value=True)
        mock_content = MagicMock()
        mock_seeder = MagicMock()
        mock_seeder.seed_all_defaults = AsyncMock(side_effect=Exception("seed exploded"))

        with patch.dict(
            "sys.modules",
            {
                "services.migrations": mock_migrations,
                "services.content_router_service": mock_content,
                "services.settings_defaults": mock_seeder,
            },
        ):
            _run(mgr._run_migrations())  # Must not raise

    def test_seed_skipped_when_no_pool(self):
        """When the DB pool is None, the seeder import path is short-circuited."""
        mgr = _make_manager()
        mgr.database_service = MagicMock()
        mgr.database_service.pool = None  # simulate degraded startup

        mock_migrations = MagicMock()
        mock_migrations.run_migrations = AsyncMock(return_value=True)
        mock_content = MagicMock()
        mock_seeder = MagicMock()
        mock_seeder.seed_all_defaults = AsyncMock(return_value=0)

        with patch.dict(
            "sys.modules",
            {
                "services.migrations": mock_migrations,
                "services.content_router_service": mock_content,
                "services.settings_defaults": mock_seeder,
            },
        ):
            _run(mgr._run_migrations())

        # No pool — seeder should not be invoked at all
        mock_seeder.seed_all_defaults.assert_not_awaited()


# ---------------------------------------------------------------------------
# _setup_redis_cache
# ---------------------------------------------------------------------------


@pytest.mark.unit
class TestSetupRedisCache:
    def test_redis_enabled_sets_cache(self):
        mgr = _make_manager()
        mock_cache = MagicMock()
        mock_cache._enabled = True
        mock_redis_cls = MagicMock()
        mock_redis_cls.create = AsyncMock(return_value=mock_cache)
        mock_module = MagicMock(RedisCache=mock_redis_cls)

        with patch.dict("sys.modules", {"services.redis_cache": mock_module}):
            _run(mgr._setup_redis_cache())

        assert mgr.redis_cache is mock_cache

    def test_redis_disabled_sets_cache_anyway(self):
        mgr = _make_manager()
        mock_cache = MagicMock()
        mock_cache._enabled = False
        mock_redis_cls = MagicMock()
        mock_redis_cls.create = AsyncMock(return_value=mock_cache)
        mock_module = MagicMock(RedisCache=mock_redis_cls)

        with patch.dict("sys.modules", {"services.redis_cache": mock_module}):
            _run(mgr._setup_redis_cache())

        assert mgr.redis_cache is mock_cache

    def test_redis_exception_warns_not_raises(self):
        mgr = _make_manager()
        mock_redis_cls = MagicMock()
        mock_redis_cls.create = AsyncMock(side_effect=Exception("connection refused"))
        mock_module = MagicMock(RedisCache=mock_redis_cls)

        with patch.dict("sys.modules", {"services.redis_cache": mock_module}):
            _run(mgr._setup_redis_cache())  # Must not raise

        assert mgr.redis_cache is None


# ---------------------------------------------------------------------------
# _initialize_task_executor — deleted in Glad-Labs/poindexter#410 Stage 4
# (2026-05-16). Prefect owns dispatch; nothing to construct in-process.
# ---------------------------------------------------------------------------


# ---------------------------------------------------------------------------
# _verify_connections
# ---------------------------------------------------------------------------


@pytest.mark.unit
class TestVerifyConnections:
    def test_healthy_database_logs_pass(self):
        mgr = _make_manager()
        mock_db = AsyncMock()
        mock_db.health_check = AsyncMock(return_value={"status": "healthy"})
        mgr.database_service = mock_db

        _run(mgr._verify_connections())

        mock_db.health_check.assert_awaited_once()

    def test_unhealthy_status_logs_warning(self):
        mgr = _make_manager()
        mock_db = AsyncMock()
        mock_db.health_check = AsyncMock(return_value={"status": "degraded"})
        mgr.database_service = mock_db

        _run(mgr._verify_connections())  # Must not raise

    def test_exception_logs_warning_not_raises(self):
        mgr = _make_manager()
        mock_db = AsyncMock()
        mock_db.health_check = AsyncMock(side_effect=Exception("health check failed"))
        mgr.database_service = mock_db

        _run(mgr._verify_connections())  # Must not raise

    def test_no_database_service_skips_check(self):
        mgr = _make_manager()
        mgr.database_service = None

        _run(mgr._verify_connections())  # Must not raise — no DB to check


# ---------------------------------------------------------------------------
# _log_startup_summary
# ---------------------------------------------------------------------------


@pytest.mark.unit
class TestLogStartupSummary:
    def test_smoke_all_none(self):
        mgr = _make_manager()
        mgr._log_startup_summary()  # Must not raise even when all services are None

    def test_smoke_with_services(self):
        mgr = _make_manager()
        mgr.database_service = MagicMock()
        mgr.redis_cache = MagicMock()
        mgr.redis_cache._enabled = True
        mgr._log_startup_summary()  # Must not raise


# ---------------------------------------------------------------------------
# shutdown
# ---------------------------------------------------------------------------


@pytest.mark.unit
class TestShutdown:
    """Shutdown sequence — Redis + DB only.

    Task dispatch lives in Prefect now (Glad-Labs/poindexter#410); the
    legacy ``self.task_executor.stop()`` call was removed in Stage 4
    (2026-05-16) alongside the deletion of ``services/task_executor.py``.
    """

    def test_shutdown_closes_redis(self):
        mgr = _make_manager()
        mock_redis = AsyncMock()
        mock_redis.close = AsyncMock()
        mgr.redis_cache = mock_redis

        _run(mgr.shutdown())

        mock_redis.close.assert_awaited_once()

    def test_shutdown_closes_database(self):
        mgr = _make_manager()
        mock_db = AsyncMock()
        mock_db.close = AsyncMock()
        mgr.database_service = mock_db

        _run(mgr.shutdown())

        mock_db.close.assert_awaited_once()

    def test_shutdown_no_services_no_crash(self):
        mgr = _make_manager()
        _run(mgr.shutdown())  # Must not raise when nothing is set


# ---------------------------------------------------------------------------
# initialize_all_services
# ---------------------------------------------------------------------------


@pytest.mark.unit
class TestInitializeAllServices:
    def _stub_all(self, mgr):
        """Stub all individual init methods so they succeed instantly."""
        mgr._validate_secrets = MagicMock()
        mgr._initialize_database = AsyncMock()
        mgr._run_migrations = AsyncMock()
        mgr._setup_redis_cache = AsyncMock()
        mgr._verify_connections = AsyncMock()
        mgr._log_startup_summary = MagicMock()

    def test_success_returns_dict_with_expected_keys(self):
        mgr = _make_manager()
        self._stub_all(mgr)

        result = _run(mgr.initialize_all_services())

        assert isinstance(result, dict)
        expected_keys = {
            "database",
            "redis_cache",
            "startup_error",
        }
        assert set(result.keys()) == expected_keys

    def test_success_startup_error_is_none(self):
        mgr = _make_manager()
        self._stub_all(mgr)

        result = _run(mgr.initialize_all_services())

        assert result["startup_error"] is None

    def test_exception_during_step_sets_startup_error_and_raises(self):
        mgr = _make_manager()
        self._stub_all(mgr)
        mgr._initialize_database = AsyncMock(side_effect=RuntimeError("DB failed"))

        with pytest.raises(RuntimeError, match="DB failed"):
            _run(mgr.initialize_all_services())

    def test_system_exit_re_raised(self):
        mgr = _make_manager()
        self._stub_all(mgr)
        mgr._initialize_database = AsyncMock(side_effect=SystemExit(1))

        with pytest.raises(SystemExit):
            _run(mgr.initialize_all_services())

    def test_exception_sets_startup_error_attribute(self):
        mgr = _make_manager()
        self._stub_all(mgr)
        mgr._run_migrations = AsyncMock(side_effect=RuntimeError("migration crashed"))

        with pytest.raises(RuntimeError):
            _run(mgr.initialize_all_services())

        assert mgr.startup_error is not None
        assert "Critical startup failure" in mgr.startup_error

    def test_log_startup_summary_called_on_success(self):
        mgr = _make_manager()
        self._stub_all(mgr)

        _run(mgr.initialize_all_services())

        mgr._log_startup_summary.assert_called_once()

    def test_all_steps_called_in_order(self):
        mgr = _make_manager()
        call_order = []

        mgr._validate_secrets = MagicMock(side_effect=lambda: call_order.append("validate"))
        mgr._initialize_database = AsyncMock(side_effect=lambda: call_order.append("db"))
        mgr._run_migrations = AsyncMock(side_effect=lambda: call_order.append("migrations"))
        mgr._setup_redis_cache = AsyncMock(side_effect=lambda: call_order.append("redis"))
        mgr._verify_connections = AsyncMock(side_effect=lambda: call_order.append("verify"))
        mgr._log_startup_summary = MagicMock()

        _run(mgr.initialize_all_services())

        assert call_order == [
            "validate",
            "db",
            "migrations",
            "redis",
            "verify",
        ]
