global:
  scrape_interval: 15s

scrape_configs:
  - job_name: nvidia-smi
    static_configs:
      - targets: ["host.docker.internal:9835"]

  - job_name: gladlabs-worker
    metrics_path: /api/prometheus
    static_configs:
      - targets: ["worker:8002"]
