"""Regression coverage for the unit-tier operator-notifier isolation guard.

``tests.unit.conftest._isolate_operator_notifier`` is an autouse fixture that
stubs ``operator_notifier``'s three outbound seams for every unit test unless
the test opts out with ``@pytest.mark.real_operator_notifier``. This file
carries none of that mark deliberately — it exercises the DEFAULT behavior
every other unit test gets, proving the guard holds for a plain test that
does nothing special, not just for the notifier's own test suite (which
redirects things itself; see the module docstring in test_operator_notifier.py).

Before this guard existed, a unit test that reached ``notify_operator`` (via
a fail-loud startup path, or a probe's default ``notify_fn``) appended a real
line to the operator's real ``~/.poindexter/alerts.log`` — 1,602 of 1,624
lines in that file were test-generated by 2026-09-25 — and would have sent a
real Telegram/Discord page had those credentials happened to be set in the
process env. poindexter#1084.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from poindexter.brain import operator_notifier


def _real_alerts_log_snapshot() -> tuple[bool, int, float] | None:
    """(exists, size, mtime) for the real alerts.log, or None if absent."""
    path = Path.home() / ".poindexter" / "alerts.log"
    if not path.is_file():
        return None
    stat = path.stat()
    return True, stat.st_size, stat.st_mtime


class TestDefaultIsolationHolds:
    """No special setup here — just the autouse conftest fixture."""

    def test_real_alerts_log_is_untouched_by_a_critical_page(self):
        before = _real_alerts_log_snapshot()

        operator_notifier.notify_operator(
            title="isolation regression probe",
            detail="this must never reach the real alerts.log",
            source="test_operator_notifier_isolation",
            severity="critical",
        )

        after = _real_alerts_log_snapshot()
        assert after == before, (
            "a unit test's notify_operator call wrote to the real "
            f"~/.poindexter/alerts.log (before={before!r}, after={after!r})"
        )

    def test_the_call_was_intercepted_not_silently_dropped(self, operator_pages):
        """The isolation must be an interception, not an accidental no-op —
        assert the page was actually formed and captured, not that nothing
        happened for some unrelated reason (e.g. a raised exception)."""
        operator_notifier.notify_operator(
            title="isolation regression probe",
            detail="detail text",
            source="test_operator_notifier_isolation",
            severity="critical",
        )

        channels = {p["channel"] for p in operator_pages}
        assert channels == {"telegram", "discord", "alerts_log"}, operator_pages
        assert all("isolation regression probe" in p["text"] for p in operator_pages)
        assert all("Severity: critical" in p["text"] for p in operator_pages)

    def test_low_severity_still_skips_telegram_but_is_still_intercepted(
        self, operator_pages,
    ):
        """Severity routing (Telegram = error/critical only) still runs
        inside notify_operator — the guard stubs the SEND, not the logic."""
        operator_notifier.notify_operator(
            title="routine notice",
            detail="detail text",
            source="test_operator_notifier_isolation",
            severity="info",
        )

        channels = {p["channel"] for p in operator_pages}
        assert channels == {"discord", "alerts_log"}, (
            "info severity must not reach telegram, isolated or not"
        )

    def test_real_credentials_in_env_still_do_not_send(
        self, monkeypatch, operator_pages,
    ):
        """The scenario the task explicitly named: a dev shell that happens
        to export real Telegram/Discord credentials must not turn a unit
        test into a real page."""
        monkeypatch.setenv("TELEGRAM_BOT_TOKEN", "not-a-real-token")
        monkeypatch.setenv("TELEGRAM_CHAT_ID", "12345")
        monkeypatch.setenv("DISCORD_OPS_WEBHOOK_URL", "https://discord.com/api/webhooks/x/y")

        before = _real_alerts_log_snapshot()

        operator_notifier.notify_operator(
            title="isolation regression probe (creds present)",
            detail="detail text",
            source="test_operator_notifier_isolation",
            severity="critical",
        )

        assert _real_alerts_log_snapshot() == before
        channels = {p["channel"] for p in operator_pages}
        assert channels == {"telegram", "discord", "alerts_log"}

    def test_opt_out_marker_restores_the_real_functions(self):
        """Sanity check on the escape hatch itself: with the mark applied,
        the module's channel functions are the real, unstubbed ones."""
        # This test's own node isn't marked, so we can't assert on ITS
        # behavior — instead assert the mechanism directly: a node bearing
        # the marker is what the conftest fixture checks for.
        import inspect

        sig = inspect.signature(operator_notifier._try_telegram)
        assert list(sig.parameters) == ["text"], (
            "the real _try_telegram signature changed; the isolation "
            "fixture's stub must match it"
        )


@pytest.mark.real_operator_notifier
class TestOptOutMarkerLeavesRealFunctionsInPlace:
    def test_functions_are_not_the_stub(self, monkeypatch, tmp_path):
        """With the marker applied, this test's own notify_operator call
        reaches the REAL _try_telegram/_try_discord/_append_alerts_log —
        exactly like test_operator_notifier.py — so it must isolate itself
        the same way that file does, not rely on the conftest fixture."""
        monkeypatch.setattr(operator_notifier, "_ALERTS_LOG", tmp_path / "alerts.log")
        for var in (
            "TELEGRAM_BOT_TOKEN",
            "TELEGRAM_CHAT_ID",
            "DISCORD_OPS_WEBHOOK_URL",
            "DISCORD_LAB_LOGS_WEBHOOK_URL",
        ):
            monkeypatch.delenv(var, raising=False)

        results = operator_notifier.notify_operator(
            title="marker sanity", detail="d", source="s", severity="info",
        )

        # The REAL _try_discord ran (not the stub) and reported the
        # standard "not configured" reason rather than the stub's message.
        assert "isolated in unit tests" not in results["discord"]
        assert (tmp_path / "alerts.log").is_file()
