"""Migration 20260713_000000: add post_content_types table

A multi-label content-type axis for published posts — the thing the niche
taxonomy (glad-labs / dev_diary) and the LLM-sprawl `tags` folksonomy can't
express. Populated by ClassifyContentTypesJob; first consumer is the Dev.to
selective-syndication gate (filter on content_type instead of niche_slug),
plus a content-type distribution Grafana panel.

Multi-label: a post carries 0..N types (e.g. an "RTX 5090 for local LLM
inference" post is {ai-ml, pc-hardware}). UNIQUE(post_id, content_type) keeps
it a set; ON DELETE CASCADE drops a deleted post's labels.

See docs/superpowers/specs/2026-07-13-content-type-classifier-design.md.
"""

from __future__ import annotations

import logging

logger = logging.getLogger(__name__)


async def up(pool) -> None:
    """Apply the migration."""
    async with pool.acquire() as conn:
        await conn.execute(
            """
            CREATE TABLE IF NOT EXISTS public.post_content_types (
                id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                post_id      uuid NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
                content_type text NOT NULL,
                confidence   real,
                source       text NOT NULL DEFAULT 'classifier',
                created_at   timestamptz NOT NULL DEFAULT now(),
                UNIQUE (post_id, content_type)
            )
            """
        )
        await conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_post_content_types_type "
            "ON post_content_types (content_type)"
        )
        await conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_post_content_types_post "
            "ON post_content_types (post_id)"
        )
    logger.info("Migration add_post_content_types: applied")


async def down(pool) -> None:
    """Revert the migration."""
    async with pool.acquire() as conn:
        await conn.execute("DROP TABLE IF EXISTS public.post_content_types")
    logger.info("Migration add_post_content_types: reverted")
