"""Migration 20260713_010000: add community-draft tables

WS2 community draft assistant. Two tables:

- subreddit_profiles: per-community config (rules, tone, post-type norms,
  self-promo tolerance, advisory karma/age/cadence gates, and the content_types
  the sub accepts) so a generated draft fits the target subreddit.
- community_post_drafts: the draft store. Distinct lifecycle from
  social_post_drafts (which is welded to the Postiz publish-gate) — these are
  manual-post drafts, blog-post-optional (IndieHackers isn't blog-tied), with a
  mark-posted-with-URL state and no auto-post surface.

Ships EMPTY. Operator subreddit seeds live in the stripped operator overlay,
never OSS baseline. See
docs/superpowers/specs/2026-07-13-community-draft-assistant-design.md.
"""

from __future__ import annotations

import logging

logger = logging.getLogger(__name__)


async def up(pool) -> None:
    """Apply the migration."""
    async with pool.acquire() as conn:
        await conn.execute(
            """
            CREATE TABLE IF NOT EXISTS public.subreddit_profiles (
                id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                subreddit            text NOT NULL UNIQUE,
                enabled              boolean NOT NULL DEFAULT true,
                content_types        text[] NOT NULL DEFAULT '{}',
                post_type            text NOT NULL DEFAULT 'text',
                self_promo           text NOT NULL DEFAULT 'strict',
                flair                text,
                min_karma            integer,
                min_account_age_days integer,
                rules_summary        text NOT NULL DEFAULT '',
                tone_notes           text NOT NULL DEFAULT '',
                cadence_cap_days     integer,
                created_at           timestamptz NOT NULL DEFAULT now(),
                updated_at           timestamptz NOT NULL DEFAULT now()
            )
            """
        )
        await conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_subreddit_profiles_enabled "
            "ON subreddit_profiles (enabled)"
        )
        await conn.execute(
            """
            CREATE TABLE IF NOT EXISTS public.community_post_drafts (
                id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                target         text NOT NULL,
                title          text,
                body           text NOT NULL,
                post_type      text NOT NULL DEFAULT 'text',
                source_post_id uuid REFERENCES posts(id) ON DELETE SET NULL,
                warnings       text[] NOT NULL DEFAULT '{}',
                status         text NOT NULL DEFAULT 'draft',
                posted_url     text,
                model          text,
                created_at     timestamptz NOT NULL DEFAULT now(),
                updated_at     timestamptz NOT NULL DEFAULT now()
            )
            """
        )
        await conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_community_post_drafts_status "
            "ON community_post_drafts (status)"
        )
    logger.info("Migration add_community_draft_tables: applied")


async def down(pool) -> None:
    """Revert the migration."""
    async with pool.acquire() as conn:
        await conn.execute("DROP TABLE IF EXISTS public.community_post_drafts")
        await conn.execute("DROP TABLE IF EXISTS public.subreddit_profiles")
    logger.info("Migration add_community_draft_tables: reverted")
