"""Migration: add ``knowledge_edges``.

ISSUE: Glad-Labs/poindexter#1035

Step 3 of the poindexter#1033 plan. The memory corpus already contains a
hand-curated knowledge graph — 938 resolved ``[[wiki-link]]`` edges across 375
files — and **nothing in the codebase has ever parsed it**. The links are
documentation-only today: `MemoryFilesTap` embeds the files as independent
chunks, so retrieval sees 375 disconnected documents and the operator's own
statement that "this incident relates to that project" is invisible to it.

This table makes that graph traversable so retrieval can expand along it
(retrieve → expand → rerank), which is the one idea worth taking from cognee:
we get it without cognee's ingestion cost because the edges are already
written by hand, not extracted by an LLM.

Deliberately generic in ``(table, id)`` pairs rather than memory-specific:
posts carry internal links and issues cross-reference each other, and both
should land here later without a second table.

Edges are DERIVED data — a full rebuild is cheap and idempotent, so there is
no need to preserve rows across a re-extract.
"""

from __future__ import annotations

import logging

logger = logging.getLogger(__name__)


async def up(pool) -> None:
    """Create the edge table plus the two indexes traversal needs.

    Both directions are indexed because expansion is undirected in practice:
    a memory that links OUT to an incident and a memory linked TO by that
    incident are equally relevant neighbours, and forcing traversal to follow
    authoring direction would drop half the graph.
    """
    async with pool.acquire() as conn:
        await conn.execute(
            """
            CREATE TABLE IF NOT EXISTS knowledge_edges (
                id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                src_table     varchar(50)  NOT NULL,
                src_id        varchar(255) NOT NULL,
                dst_table     varchar(50)  NOT NULL,
                dst_id        varchar(255) NOT NULL,
                relation      varchar(50)  NOT NULL DEFAULT 'links_to',
                weight        double precision NOT NULL DEFAULT 1.0,
                origin        varchar(50)  NOT NULL DEFAULT 'memory_wikilink',
                created_at    timestamptz  NOT NULL DEFAULT now(),
                updated_at    timestamptz  NOT NULL DEFAULT now()
            )
            """
        )
        # Natural key: one edge per (src, dst, relation). Re-extraction upserts
        # rather than duplicating.
        await conn.execute(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS ux_knowledge_edges_natural
                ON knowledge_edges (src_table, src_id, dst_table, dst_id, relation)
            """
        )
        await conn.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_knowledge_edges_src
                ON knowledge_edges (src_table, src_id)
            """
        )
        await conn.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_knowledge_edges_dst
                ON knowledge_edges (dst_table, dst_id)
            """
        )
        await conn.execute(
            """
            COMMENT ON TABLE knowledge_edges IS
            'Traversable relationships between indexed documents (poindexter#1035). '
            'Derived data — rebuild with ExtractKnowledgeEdgesJob; safe to truncate.'
            """
        )
    logger.info("Migration: knowledge_edges created")


async def down(pool) -> None:
    """Drop the table. Safe — it is derived and rebuildable from the sources."""
    async with pool.acquire() as conn:
        await conn.execute("DROP TABLE IF EXISTS knowledge_edges")
    logger.info("Migration: knowledge_edges dropped")
