#!/usr/bin/env bash
#
# Bootstrap Script — One-command setup for the AI Content Pipeline
#
# Usage:
#   bash scripts/bootstrap.sh
#
# What it does:
#   1. Checks prerequisites (Docker, Node.js, Python, Ollama)
#   2. Starts infrastructure (PostgreSQL + pgvector, Grafana)
#   3. Runs database migrations
#   4. Seeds default app_settings (all configurable, no hardcoding)
#   5. Pulls required Ollama models
#   6. Installs dependencies
#   7. Prints next steps
#
# After running this, you can:
#   - Start the full stack: docker compose -f docker-compose.local.yml up -d
#   - View dashboards: http://localhost:3000 (Grafana, password in .env.local)

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info()  { echo -e "${BLUE}[INFO]${NC} $1"; }
ok()    { echo -e "${GREEN}[OK]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
fail()  { echo -e "${RED}[FAIL]${NC} $1"; exit 1; }

# ============================================================
# 1. Prerequisites
# ============================================================
info "Checking prerequisites..."

command -v docker >/dev/null 2>&1 || fail "Docker not found. Install: https://docker.com"
command -v node >/dev/null 2>&1 || fail "Node.js not found. Install: https://nodejs.org (v22+)"
command -v python3 >/dev/null 2>&1 || command -v python >/dev/null 2>&1 || fail "Python not found. Install: https://python.org (3.12+)"
command -v ollama >/dev/null 2>&1 || warn "Ollama not found. Install: https://ollama.com — needed for local LLM inference"
command -v psql >/dev/null 2>&1 || warn "psql (postgresql-client) not found — the settings-seed step will be skipped. The worker container runs migrations regardless, but you will miss the seeded defaults in app_settings. Install postgresql-client to fix."
command -v openssl >/dev/null 2>&1 || warn "openssl not found — will fall back to python3 for secret generation"

ok "Prerequisites found"

# ============================================================
# 2. Environment configuration
# ============================================================
if [ ! -f .env.local ]; then
    info "Creating .env.local from template..."
    if [ -f .env.example ]; then
        cp .env.example .env.local

        # Auto-generate required secrets. Hard-fail if neither openssl nor
        # python3 is available — a deterministic fallback would silently
        # produce predictable secrets and we'd rather the customer install
        # an entropy source than ship with broken auth.
        _gen_secret() {
            openssl rand -base64 "$1" 2>/dev/null || \
                python3 -c "import secrets; print(secrets.token_urlsafe($1))" 2>/dev/null || \
                fail "Cannot generate secrets: install openssl or python3 with the secrets module"
        }
        _api_token=$(_gen_secret 32)
        _grafana_pw=$(_gen_secret 16)
        _pg_pw=$(_gen_secret 16)
        _pgadmin_pw=$(_gen_secret 16)
        _woodpecker_secret=$(_gen_secret 24)
        _glitchtip_db_pw=$(_gen_secret 16)
        _glitchtip_secret=$(_gen_secret 32)

        # Write generated secrets into .env.local
        {
            echo ""
            echo "# Auto-generated by bootstrap.sh on $(date -Iseconds 2>/dev/null || date)"
            echo "API_TOKEN=${_api_token}"
            echo "GRAFANA_PASSWORD=${_grafana_pw}"
            echo "LOCAL_POSTGRES_PASSWORD=${_pg_pw}"
            echo "PGADMIN_PASSWORD=${_pgadmin_pw}"
            echo "WOODPECKER_SECRET=${_woodpecker_secret}"
            echo "GLITCHTIP_DB_PASSWORD=${_glitchtip_db_pw}"
            echo "GLITCHTIP_SECRET_KEY=${_glitchtip_secret}"
        } >> .env.local

        ok ".env.local created with auto-generated secrets"
        info "Review .env.local and customize site settings before starting"
    else
        warn "No .env.example found — create .env.local manually"
    fi
else
    ok ".env.local already exists"
fi

# Source env vars for the rest of the script
if [ -f .env.local ]; then
    set -a
    source .env.local 2>/dev/null || true
    set +a
fi

# ============================================================
# 3. Start infrastructure
# ============================================================
info "Starting infrastructure (PostgreSQL + pgvector, Grafana)..."

docker compose -f docker-compose.local.yml up -d postgres-local grafana 2>/dev/null || \
    docker-compose -f docker-compose.local.yml up -d postgres-local grafana 2>/dev/null || \
    fail "Failed to start Docker containers. Is Docker running?"

# Wait for PostgreSQL to be ready
info "Waiting for PostgreSQL..."
for i in $(seq 1 30); do
    if docker exec poindexter-postgres-local pg_isready -U "${LOCAL_POSTGRES_USER:-poindexter}" -d "${LOCAL_POSTGRES_DB:-poindexter_brain}" >/dev/null 2>&1; then
        ok "PostgreSQL ready"
        break
    fi
    if [ "$i" -eq 30 ]; then
        fail "PostgreSQL didn't start in 30 seconds"
    fi
    sleep 1
done

# ============================================================
# 4. Install dependencies
# ============================================================
info "Installing Node.js dependencies..."
npm ci 2>/dev/null || npm install

info "Installing Python dependencies..."
cd src/cofounder_agent
if command -v poetry >/dev/null 2>&1; then
    poetry install --no-root
else
    pip install poetry
    poetry install --no-root
fi
cd ../..

ok "Dependencies installed"

# ============================================================
# 5. Verify database connectivity
# ============================================================
info "Verifying database connectivity..."
if PGPASSWORD="${LOCAL_POSTGRES_PASSWORD:-poindexter-brain-local}" psql -h localhost -p 15432 -U "${LOCAL_POSTGRES_USER:-poindexter}" -d "${LOCAL_POSTGRES_DB:-poindexter_brain}" -c "SELECT 1" >/dev/null 2>&1; then
    ok "Database reachable (migrations will run automatically when the worker starts)"
else
    warn "Database not reachable via psql — this is OK if psql is not installed"
    info "The worker container runs all migrations automatically on first boot"
fi

# ============================================================
# 6. Seed default settings
# ============================================================
info "Seeding default app_settings..."

# These are the configurable knobs — change them in the DB, not in code
PGPASSWORD="${LOCAL_POSTGRES_PASSWORD:-poindexter-brain-local}" psql -h localhost -p 15432 -U "${LOCAL_POSTGRES_USER:-poindexter}" -d "${LOCAL_POSTGRES_DB:-poindexter_brain}" -c "
CREATE TABLE IF NOT EXISTS app_settings (
    id SERIAL PRIMARY KEY,
    key VARCHAR(255) UNIQUE NOT NULL,
    value TEXT DEFAULT '',
    category VARCHAR(100) DEFAULT 'general',
    description TEXT DEFAULT '',
    is_secret BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO app_settings (key, value, category, description, is_secret) VALUES
-- Site identity (CHANGE THESE)
('site_name', 'My Content Site', 'site', 'Your site/brand name', false),
('site_domain', 'localhost:3000', 'site', 'Production domain (e.g. example.com)', false),
('site_description', 'AI-powered content platform', 'site', 'Site meta description', false),
('api_base_url', 'http://localhost:8000', 'site', 'Backend API URL', false),

-- Quality thresholds
('qa_overall_score_threshold', '70', 'quality', 'Minimum quality score to pass QA (0-100)', false),
('qa_final_score_threshold', '70', 'quality', 'Multi-model QA approval threshold', false),
('qa_critical_dimension_floor', '50', 'quality', 'Minimum score on any single dimension', false),
('qa_validator_weight', '0.4', 'quality', 'Weight for programmatic validator', false),
('qa_critic_weight', '0.6', 'quality', 'Weight for LLM critic', false),

-- Model selections — defaults match what Ollama models are auto-pulled
-- below. Override these in app_settings (or via the API) once you've
-- pulled a larger writer/critic model. See README for upgrade options.
('pipeline_writer_model', 'ollama/qwen3:8b', 'models', 'Content generation model', false),
('pipeline_critic_model', 'ollama/gemma3:27b', 'models', 'QA/review model', false),
('pipeline_seo_model', 'ollama/qwen3:8b', 'models', 'SEO metadata model', false),
('pipeline_social_model', 'ollama/qwen3:8b', 'models', 'Social post generation model', false),
('pipeline_fallback_model', 'ollama/gemma3:27b', 'models', 'Fallback when primary unavailable', false),

-- Token limits
('qa_thinking_model_max_tokens', '8000', 'tokens', 'Max tokens for thinking models in QA', false),
('qa_standard_max_tokens', '1500', 'tokens', 'Max tokens for standard models in QA', false),
('qa_temperature', '0.3', 'tokens', 'Temperature for QA reviews', false),
('content_temperature', '0.7', 'tokens', 'Temperature for content generation', false),
('max_tokens_default', '800', 'tokens', 'Default max tokens', false),

-- Content rules
('content_min_word_count', '800', 'content', 'Minimum word count for posts', false),
('content_target_word_count', '1500', 'content', 'Target word count', false),
('content_max_refinement_attempts', '3', 'content', 'Max quality refinement attempts', false),

-- Cost limits
('daily_spend_limit', '2.0', 'cost', 'Max daily cloud API spend (USD)', false),
('monthly_spend_limit', '10.0', 'cost', 'Max monthly cloud API spend (USD)', false),
('cost_alert_threshold_pct', '80', 'cost', 'Alert when spend exceeds this %', false),
('ollama_electricity_cost_per_1k_tokens', '0.000256', 'cost', 'Ollama electricity cost per 1K tokens', false),

-- Pipeline config
('max_task_retries', '3', 'pipeline', 'Max retry attempts for failed tasks', false),
('stale_task_timeout_minutes', '60', 'pipeline', 'Minutes before stale task reset', false),
('task_sweep_interval_seconds', '300', 'pipeline', 'Seconds between stale task sweeps', false),

-- Image config
('enable_featured_image', 'true', 'image', 'Generate/search featured images', false),
('image_primary_source', 'pexels', 'image', 'Image source: pexels or ai_generation', false)
ON CONFLICT (key) DO NOTHING;
" 2>/dev/null && ok "Default settings seeded" || warn "Settings seed skipped (table may not exist yet — will be created on first backend start)"

# ============================================================
# 7. Detect hardware and recommend models
# ============================================================
info "Detecting hardware..."
if command -v python3 >/dev/null 2>&1; then
    python3 scripts/detect-hardware.py || warn "Hardware detection failed (non-critical)"
elif command -v python >/dev/null 2>&1; then
    python scripts/detect-hardware.py || warn "Hardware detection failed (non-critical)"
else
    warn "Python not available for hardware detection — using default model recommendations"
fi

# ============================================================
# 8. Pull Ollama models (based on hardware detection)
# ============================================================
if command -v ollama >/dev/null 2>&1; then
    # Check Ollama is actually running
    if curl -s http://localhost:11434/api/tags >/dev/null 2>&1; then
        ok "Ollama is running"
        info "Pulling minimum required models (this may take a while)..."
        # Stderr stays unsuppressed on `ollama pull` — pull failures
        # (disk full, network, manifest 404) are worth showing to the
        # operator before the single-line warn at end of chain.
        ollama pull nomic-embed-text && ok "nomic-embed-text (embeddings)" || warn "Failed to pull nomic-embed-text — see error above"
        ollama pull qwen3:8b && ok "qwen3:8b (fast tasks, image decisions, SEO)" || warn "Failed to pull qwen3:8b — see error above"
        ollama pull gemma3:27b && ok "gemma3:27b (QA reviews, fallback)" || warn "Failed to pull gemma3:27b — see error above"
        info ""
        info "Minimum models pulled. For better writing quality, also pull a larger model:"
        info "  ollama pull qwen3:30b     # Good balance of speed and quality (18GB)"
        info "  ollama pull glm-4.7:9b    # Lighter alternative"
        info ""
        info "Or run: python scripts/detect-hardware.py --write-db"
        info "This auto-selects the best models for your GPU and saves to the database."
    else
        warn "Ollama is installed but not running. Start it with: ollama serve"
        warn "Then re-run this script to pull models, or pull manually:"
        warn "  ollama pull qwen3:8b gemma3:27b nomic-embed-text"
    fi
else
    warn "Ollama not installed — skip model pulls. Install from https://ollama.com"
    warn "Minimum models needed: qwen3:8b (fast tasks), gemma3:27b (QA reviews)"
fi

# ============================================================
# Done!
# ============================================================
echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  Setup complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "Next steps:"
echo "  1. Bring up the full stack:"
echo "     docker compose -f docker-compose.local.yml up -d"
echo "  2. Wait for the worker to be healthy (about 30-60s):"
echo "     docker compose -f docker-compose.local.yml ps worker"
echo "  3. View Grafana dashboards at http://localhost:3000"
echo "     login: admin / \$(grep ^GRAFANA_PASSWORD .env.local | cut -d= -f2)"
echo "  4. Create your first post:"
echo "     curl -X POST http://localhost:8002/api/tasks \\"
echo "       -H \"Authorization: Bearer \$(grep ^API_TOKEN .env.local | cut -d= -f2)\" \\"
echo "       -H 'Content-Type: application/json' \\"
echo "       -d '{\"topic\": \"Your first AI-generated post\", \"category\": \"technology\"}'"
echo ""
echo "All settings are configurable in the database (app_settings table)."
echo "Change a value → pipeline uses it on the next run. No code changes needed."
echo ""
