#!/usr/bin/env bash
#
# Bootstrap Script — One-command setup for the AI Content Pipeline
#
# Usage:
#   bash scripts/bootstrap.sh
#
# What it does:
#   1. Checks prerequisites (Docker, Node.js, Python, Ollama)
#   2. Writes the environment configuration
#   3. Starts infrastructure (PostgreSQL + pgvector, Grafana)
#   4. Installs Node.js and Python dependencies
#   5. Verifies database connectivity
#   6. Detects hardware
#   7. Pulls the required Ollama models
#   8. Prints next steps
#
# Migrations and the app_settings seed are not its job: the worker runs the
# migrations and the brain daemon seeds the core settings when the stack comes up.
#
# After running this, you can:
#   - Start the full stack: docker compose -f docker-compose.local.yml up -d
#   - View dashboards: http://localhost:3000 (Grafana, password in .env.local)

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info()  { echo -e "${BLUE}[INFO]${NC} $1"; }
ok()    { echo -e "${GREEN}[OK]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
fail()  { echo -e "${RED}[FAIL]${NC} $1"; exit 1; }

# ============================================================
# 1. Prerequisites
# ============================================================
info "Checking prerequisites..."

command -v docker >/dev/null 2>&1 || fail "Docker not found. Install: https://docker.com"
command -v node >/dev/null 2>&1 || fail "Node.js not found. Install: https://nodejs.org (v22+)"
command -v python3 >/dev/null 2>&1 || command -v python >/dev/null 2>&1 || fail "Python not found. Install: https://python.org (3.12+)"
command -v ollama >/dev/null 2>&1 || warn "Ollama not found. Install: https://ollama.com — needed for local LLM inference"
command -v psql >/dev/null 2>&1 || warn "psql (postgresql-client) not found — the database connectivity check will be skipped. That is non-critical: the worker container runs migrations regardless. Install postgresql-client to run the check."
command -v openssl >/dev/null 2>&1 || warn "openssl not found — will fall back to python3 for secret generation"

ok "Prerequisites found"

# ============================================================
# 2. Environment configuration
# ============================================================
if [ ! -f .env.local ]; then
    info "Creating .env.local from template..."
    if [ -f .env.example ]; then
        cp .env.example .env.local

        # Auto-generate required secrets. Hard-fail if neither openssl nor
        # python3 is available — a deterministic fallback would silently
        # produce predictable secrets and we'd rather the customer install
        # an entropy source than ship with broken auth.
        _gen_secret() {
            openssl rand -base64 "$1" 2>/dev/null || \
                python3 -c "import secrets; print(secrets.token_urlsafe($1))" 2>/dev/null || \
                fail "Cannot generate secrets: install openssl or python3 with the secrets module"
        }
        _api_token=$(_gen_secret 32)
        _grafana_pw=$(_gen_secret 16)
        _pg_pw=$(_gen_secret 16)
        _pgadmin_pw=$(_gen_secret 16)
        _woodpecker_secret=$(_gen_secret 24)
        _glitchtip_db_pw=$(_gen_secret 16)
        _glitchtip_secret=$(_gen_secret 32)

        # Write generated secrets into .env.local
        {
            echo ""
            echo "# Auto-generated by bootstrap.sh on $(date -Iseconds 2>/dev/null || date)"
            echo "API_TOKEN=${_api_token}"
            echo "GRAFANA_PASSWORD=${_grafana_pw}"
            echo "LOCAL_POSTGRES_PASSWORD=${_pg_pw}"
            echo "PGADMIN_PASSWORD=${_pgadmin_pw}"
            echo "WOODPECKER_SECRET=${_woodpecker_secret}"
            echo "GLITCHTIP_DB_PASSWORD=${_glitchtip_db_pw}"
            echo "GLITCHTIP_SECRET_KEY=${_glitchtip_secret}"
        } >> .env.local

        ok ".env.local created with auto-generated secrets"
        info "Review .env.local and customize site settings before starting"
    else
        warn "No .env.example found — create .env.local manually"
    fi
else
    ok ".env.local already exists"
fi

# Source env vars for the rest of the script
if [ -f .env.local ]; then
    set -a
    source .env.local 2>/dev/null || true
    set +a
fi

# ============================================================
# 3. Start infrastructure
# ============================================================
info "Starting infrastructure (PostgreSQL + pgvector, Grafana)..."

docker compose -f docker-compose.local.yml up -d postgres-local grafana 2>/dev/null || \
    docker-compose -f docker-compose.local.yml up -d postgres-local grafana 2>/dev/null || \
    fail "Failed to start Docker containers. Is Docker running?"

# Wait for PostgreSQL to be ready
info "Waiting for PostgreSQL..."
for i in $(seq 1 30); do
    if docker exec poindexter-postgres-local pg_isready -U "${LOCAL_POSTGRES_USER:-poindexter}" -d "${LOCAL_POSTGRES_DB:-poindexter_brain}" >/dev/null 2>&1; then
        ok "PostgreSQL ready"
        break
    fi
    if [ "$i" -eq 30 ]; then
        fail "PostgreSQL didn't start in 30 seconds"
    fi
    sleep 1
done

# ============================================================
# 4. Install dependencies
# ============================================================
info "Installing Node.js dependencies..."
npm ci 2>/dev/null || npm install

info "Installing Python dependencies..."
cd src/cofounder_agent
# --extras rerank keeps the local dev env's cross-encoder reranker working
# (sentence-transformers + torch). CI installs lean (torch-free) since the
# 2026-06-23 rerank-extra trim; the host opts in here so a fresh setup matches
# what the worker runs. See docs/superpowers/specs/2026-06-23-ci-rerank-extra-design.md.
if command -v poetry >/dev/null 2>&1; then
    poetry install --no-root --extras "rerank pipeline qa rag"
else
    pip install poetry
    poetry install --no-root --extras "rerank pipeline qa rag"
fi
cd ../..

ok "Dependencies installed"

# ============================================================
# 5. Verify database connectivity
# ============================================================
# Read-only on purpose. This script never creates or seeds app_settings: the
# worker's migrations create it, and the brain daemon seeds the free-tier core
# settings on first boot (poindexter/brain/seed_loader.py). A copy made here runs
# before either exists, so it wins the first-writer race with whatever it
# carries, and a table it creates narrower than the baseline's crashed the
# worker's migration (poindexter#1097).
info "Verifying database connectivity..."
# No default password: LOCAL_POSTGRES_PASSWORD is generated per install
# (above, or by `poindexter setup`), so a literal fallback could only fail.
if [ -z "${LOCAL_POSTGRES_PASSWORD:-}" ]; then
    warn "LOCAL_POSTGRES_PASSWORD is not set — skipping the database check"
    info "Run 'poindexter setup' or set it in .env.local, then re-run this script"
elif PGPASSWORD="${LOCAL_POSTGRES_PASSWORD}" psql -h localhost -p "${POSTGRES_HOST_PORT:-5433}" -U "${LOCAL_POSTGRES_USER:-poindexter}" -d "${LOCAL_POSTGRES_DB:-poindexter_brain}" -c "SELECT 1" >/dev/null 2>&1; then
    ok "Database reachable (migrations will run automatically when the worker starts)"
else
    warn "Database not reachable via psql — this is OK if psql is not installed"
    info "The worker container runs all migrations automatically on first boot"
fi

# ============================================================
# 6. Detect hardware and recommend models
# ============================================================
info "Detecting hardware..."
if command -v python3 >/dev/null 2>&1; then
    python3 scripts/detect-hardware.py || warn "Hardware detection failed (non-critical)"
elif command -v python >/dev/null 2>&1; then
    python scripts/detect-hardware.py || warn "Hardware detection failed (non-critical)"
else
    warn "Python not available for hardware detection — using default model recommendations"
fi

# ============================================================
# 7. Pull Ollama models (based on hardware detection)
# ============================================================
if command -v ollama >/dev/null 2>&1; then
    # Check Ollama is actually running
    if curl -s http://localhost:11434/api/tags >/dev/null 2>&1; then
        ok "Ollama is running"
        info "Pulling minimum required models (this may take a while)..."
        # Stderr stays unsuppressed on `ollama pull` — pull failures
        # (disk full, network, manifest 404) are worth showing to the
        # operator before the single-line warn at end of chain.
        ollama pull nomic-embed-text && ok "nomic-embed-text (embeddings)" || warn "Failed to pull nomic-embed-text — see error above"
        # CPU-pin the embedding model so it doesn't evict the writer model from VRAM.
        # The app_settings embed_num_gpu=0 passes num_gpu:0 to every embed call, but
        # baking it into the Modelfile makes it permanent even for callers that don't
        # pass options. This overwrites the base model in-place (same name).
        _mf=$(mktemp)
        printf 'FROM nomic-embed-text\nPARAMETER num_gpu 0\n' > "${_mf}"
        ollama create nomic-embed-text -f "${_mf}" && ok "nomic-embed-text CPU-pinned (Modelfile)" || warn "Failed to CPU-pin nomic-embed-text via Modelfile — embed calls will still pass num_gpu=0 via options"
        rm -f "${_mf}"
        ollama pull qwen3:8b && ok "qwen3:8b (fast tasks, image decisions, SEO)" || warn "Failed to pull qwen3:8b — see error above"
        ollama pull gemma3:27b && ok "gemma3:27b (QA reviews, fallback)" || warn "Failed to pull gemma3:27b — see error above"
        info ""
        info "Minimum models pulled. For better writing quality, also pull a larger model:"
        info "  ollama pull qwen3:30b     # Good balance of speed and quality (18GB)"
        info "  ollama pull glm-4.7:9b    # Lighter alternative"
        info ""
        info "Or run: python scripts/detect-hardware.py --write-db"
        info "This auto-selects the best models for your GPU and saves to the database."
    else
        warn "Ollama is installed but not running. Start it with: ollama serve"
        warn "Then re-run this script to pull models, or pull manually:"
        warn "  ollama pull qwen3:8b gemma3:27b nomic-embed-text"
    fi
else
    warn "Ollama not installed — skip model pulls. Install from https://ollama.com"
    warn "Minimum models needed: qwen3:8b (fast tasks), gemma3:27b (QA reviews)"
fi

# ============================================================
# Done!
# ============================================================
echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  Setup complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "Next steps:"
echo "  1. Bring up the full stack:"
echo "     docker compose -f docker-compose.local.yml up -d"
echo "  2. Wait for the worker to be healthy (about 30-60s):"
echo "     docker compose -f docker-compose.local.yml ps worker"
echo "  3. View Grafana dashboards at http://localhost:3000"
echo "     login: admin / \$(grep ^GRAFANA_PASSWORD .env.local | cut -d= -f2)"
echo "  4. Create your first post:"
echo "     curl -X POST http://localhost:8002/api/tasks \\"
echo "       -H \"Authorization: Bearer \$(grep ^API_TOKEN .env.local | cut -d= -f2)\" \\"
echo "       -H 'Content-Type: application/json' \\"
echo "       -d '{\"topic\": \"Your first AI-generated post\", \"category\": \"technology\"}'"
echo ""
echo "All settings are configurable in the database (app_settings table)."
echo "Change a value → pipeline uses it on the next run. No code changes needed."
echo ""
