"""
Migrate Operational Tables from Railway (Cloud) to Local pgvector DB

Copies DDL + data for operational tables from the Railway Postgres instance
to the local gladlabs_brain database. Safe to run multiple times — uses
INSERT ... ON CONFLICT DO NOTHING so duplicate rows are skipped.

Does NOT delete anything from the cloud database.
Does NOT touch the local embeddings/memory tables.

Usage:
    python scripts/migrate-to-local-db.py
"""

import asyncio
import sys
import time

import asyncpg

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

CLOUD_DSN = (
    "postgresql://postgres:***REMOVED***"
    "@hopper.proxy.rlwy.net:32382/railway"
)
LOCAL_DSN = (
    "postgresql://gladlabs:gladlabs-brain-local@localhost:5433/gladlabs_brain"
)

TABLES_TO_MIGRATE = [
    "content_tasks",
    "cost_logs",
    "brain_knowledge",
    "brain_queue",
    "brain_decisions",
    "orchestrator_training_data",
    "quality_evaluations",
    "task_status_history",
    "routing_outcomes",
    "content_calendar",
    "pipeline_events",
    "webhook_events",
]

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


async def get_table_ddl(conn: asyncpg.Connection, table: str) -> str | None:
    """Fetch the CREATE TABLE statement for a table from the cloud DB.

    Uses pg_dump-style reconstruction via pg_get_tabledef isn't available in
    vanilla PG, so we query information_schema + pg_indexes instead.
    """
    # Check table exists
    exists = await conn.fetchval(
        """
        SELECT EXISTS (
            SELECT 1 FROM information_schema.tables
            WHERE table_schema = 'public' AND table_name = $1
        )
        """,
        table,
    )
    if not exists:
        return None

    # Get column definitions
    cols = await conn.fetch(
        """
        SELECT column_name, data_type, udt_name,
               column_default, is_nullable,
               character_maximum_length, numeric_precision, numeric_scale
        FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = $1
        ORDER BY ordinal_position
        """,
        table,
    )
    if not cols:
        return None

    col_defs = []
    for c in cols:
        name = c["column_name"]
        # Use udt_name for user-defined / array types, data_type otherwise
        dtype = c["udt_name"]
        if dtype.startswith("_"):
            # Array type, e.g. _text -> text[]
            dtype = dtype[1:] + "[]"
        elif c["data_type"] == "character varying":
            length = c["character_maximum_length"]
            dtype = f"varchar({length})" if length else "text"
        elif c["data_type"] == "numeric" and c["numeric_precision"]:
            dtype = f"numeric({c['numeric_precision']},{c['numeric_scale'] or 0})"
        elif c["data_type"] in ("timestamp with time zone",):
            dtype = "timestamptz"
        elif c["data_type"] in ("timestamp without time zone",):
            dtype = "timestamp"
        elif c["data_type"] == "USER-DEFINED":
            # Already got udt_name above (e.g. vector, custom enum)
            pass

        nullable = "" if c["is_nullable"] == "YES" else " NOT NULL"
        col_default = c["column_default"] or ""

        # Convert nextval() serial columns to GENERATED BY DEFAULT AS IDENTITY
        if "nextval(" in col_default:
            col_defs.append(f'    "{name}" {dtype} GENERATED BY DEFAULT AS IDENTITY{nullable}')
        else:
            default = f" DEFAULT {col_default}" if col_default else ""
            col_defs.append(f'    "{name}" {dtype}{default}{nullable}')

    # Get primary key
    pk = await conn.fetch(
        """
        SELECT kcu.column_name
        FROM information_schema.table_constraints tc
        JOIN information_schema.key_column_usage kcu
            ON tc.constraint_name = kcu.constraint_name
            AND tc.table_schema = kcu.table_schema
        WHERE tc.table_schema = 'public'
            AND tc.table_name = $1
            AND tc.constraint_type = 'PRIMARY KEY'
        ORDER BY kcu.ordinal_position
        """,
        table,
    )
    if pk:
        pk_cols = ", ".join(f'"{r["column_name"]}"' for r in pk)
        col_defs.append(f"    PRIMARY KEY ({pk_cols})")

    ddl = f'CREATE TABLE IF NOT EXISTS "{table}" (\n'
    ddl += ",\n".join(col_defs)
    ddl += "\n);"

    return ddl


async def get_primary_key_columns(conn: asyncpg.Connection, table: str) -> list[str]:
    """Return list of PK column names for a table."""
    rows = await conn.fetch(
        """
        SELECT kcu.column_name
        FROM information_schema.table_constraints tc
        JOIN information_schema.key_column_usage kcu
            ON tc.constraint_name = kcu.constraint_name
            AND tc.table_schema = kcu.table_schema
        WHERE tc.table_schema = 'public'
            AND tc.table_name = $1
            AND tc.constraint_type = 'PRIMARY KEY'
        ORDER BY kcu.ordinal_position
        """,
        table,
    )
    return [r["column_name"] for r in rows]


async def get_indexes(conn: asyncpg.Connection, table: str) -> list[str]:
    """Return CREATE INDEX statements for non-PK indexes on a table."""
    rows = await conn.fetch(
        """
        SELECT indexdef
        FROM pg_indexes
        WHERE schemaname = 'public'
            AND tablename = $1
            AND indexname NOT IN (
                SELECT constraint_name FROM information_schema.table_constraints
                WHERE table_schema = 'public' AND table_name = $1
                    AND constraint_type = 'PRIMARY KEY'
            )
        """,
        table,
    )
    # Rewrite CREATE INDEX to CREATE INDEX IF NOT EXISTS
    result = []
    for r in rows:
        stmt = r["indexdef"]
        stmt = stmt.replace("CREATE INDEX ", "CREATE INDEX IF NOT EXISTS ", 1)
        stmt = stmt.replace("CREATE UNIQUE INDEX ", "CREATE UNIQUE INDEX IF NOT EXISTS ", 1)
        result.append(stmt + ";")
    return result


async def table_exists_locally(conn: asyncpg.Connection, table: str) -> bool:
    return await conn.fetchval(
        """
        SELECT EXISTS (
            SELECT 1 FROM information_schema.tables
            WHERE table_schema = 'public' AND table_name = $1
        )
        """,
        table,
    )


async def get_column_names(conn: asyncpg.Connection, table: str) -> list[str]:
    rows = await conn.fetch(
        """
        SELECT column_name FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = $1
        ORDER BY ordinal_position
        """,
        table,
    )
    return [r["column_name"] for r in rows]


async def check_enum_types(cloud: asyncpg.Connection, local: asyncpg.Connection):
    """Copy any custom enum types from cloud that don't exist locally."""
    enums = await cloud.fetch(
        """
        SELECT t.typname, string_agg(e.enumlabel, ',' ORDER BY e.enumsortorder) AS labels
        FROM pg_type t
        JOIN pg_enum e ON t.oid = e.enumtypid
        JOIN pg_namespace n ON t.typnamespace = n.oid
        WHERE n.nspname = 'public'
        GROUP BY t.typname
        """
    )
    for enum in enums:
        name = enum["typname"]
        labels = enum["labels"].split(",")
        exists = await local.fetchval(
            "SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = $1)", name
        )
        if not exists:
            labels_sql = ", ".join(f"'{l}'" for l in labels)
            await local.execute(f'CREATE TYPE "{name}" AS ENUM ({labels_sql});')
            print(f"  Created enum type: {name}")


# ---------------------------------------------------------------------------
# Main migration
# ---------------------------------------------------------------------------


async def migrate_table(
    cloud: asyncpg.Connection,
    local: asyncpg.Connection,
    table: str,
) -> tuple[int, int, int]:
    """Migrate a single table. Returns (total_cloud, copied, skipped)."""

    # Check if table exists on cloud
    cloud_exists = await cloud.fetchval(
        "SELECT EXISTS (SELECT 1 FROM information_schema.tables "
        "WHERE table_schema='public' AND table_name=$1)",
        table,
    )
    if not cloud_exists:
        print(f"  [{table}] does not exist on cloud -- skipping")
        return (0, 0, 0)

    # Create table locally if needed
    if not await table_exists_locally(local, table):
        ddl = await get_table_ddl(cloud, table)
        if not ddl:
            print(f"  [{table}] could not generate DDL -- skipping")
            return (0, 0, 0)
        await local.execute(ddl)
        # Also create indexes
        indexes = await get_indexes(cloud, table)
        for idx_stmt in indexes:
            try:
                await local.execute(idx_stmt)
            except Exception as e:
                print(f"  [{table}] index warning: {e}")
        print(f"  [{table}] created table locally")
    else:
        print(f"  [{table}] table already exists locally")

    # Get columns and PK
    columns = await get_column_names(cloud, table)
    pk_cols = await get_primary_key_columns(cloud, table)

    # Count cloud rows
    total_cloud = await cloud.fetchval(f'SELECT count(*) FROM "{table}"')
    if total_cloud == 0:
        print(f"  [{table}] 0 rows on cloud -- nothing to copy")
        return (0, 0, 0)

    # Count local rows before
    local_before = await local.fetchval(f'SELECT count(*) FROM "{table}"')

    # Fetch all rows from cloud
    rows = await cloud.fetch(f'SELECT * FROM "{table}"')

    # Build INSERT ... ON CONFLICT DO NOTHING
    col_list = ", ".join(f'"{c}"' for c in columns)
    placeholders = ", ".join(f"${i+1}" for i in range(len(columns)))

    if pk_cols:
        conflict_cols = ", ".join(f'"{c}"' for c in pk_cols)
        conflict_clause = f"ON CONFLICT ({conflict_cols}) DO NOTHING"
    else:
        # No PK -- can't do ON CONFLICT, use a workaround:
        # insert only, duplicates may appear if re-run (warn user)
        conflict_clause = ""
        print(f"  [{table}] WARNING: no primary key -- duplicates possible on re-run")

    insert_sql = (
        f'INSERT INTO "{table}" ({col_list}) VALUES ({placeholders}) {conflict_clause}'
    )

    # Batch insert
    batch_size = 500
    for i in range(0, len(rows), batch_size):
        batch = rows[i : i + batch_size]
        # Use executemany for speed
        await local.executemany(
            insert_sql,
            [tuple(row[c] for c in columns) for row in batch],
        )

    # Count local rows after
    local_after = await local.fetchval(f'SELECT count(*) FROM "{table}"')
    copied = local_after - local_before
    skipped = total_cloud - copied

    return (total_cloud, copied, skipped)


async def main():
    print("=" * 60)
    print("Glad Labs: Migrate Operational Tables to Local DB")
    print("=" * 60)
    print()

    # Connect
    print("Connecting to Cloud (Railway)...")
    cloud = await asyncpg.connect(CLOUD_DSN)
    print("Connecting to Local DB...")
    local = await asyncpg.connect(LOCAL_DSN)

    print()
    print("Checking for custom enum types...")
    await check_enum_types(cloud, local)
    print()

    results = []
    for table in TABLES_TO_MIGRATE:
        print(f"Migrating: {table}")
        t0 = time.time()
        total, copied, skipped = await migrate_table(cloud, local, table)
        elapsed = time.time() - t0
        results.append((table, total, copied, skipped, elapsed))
        if total > 0:
            print(
                f"  -> {total} cloud rows | {copied} copied | {skipped} skipped | {elapsed:.1f}s"
            )
        print()

    # Summary
    print("=" * 60)
    print(f"{'Table':<30} {'Cloud':>6} {'Copied':>7} {'Skipped':>8}")
    print("-" * 60)
    total_copied = 0
    total_skipped = 0
    for table, total, copied, skipped, elapsed in results:
        print(f"{table:<30} {total:>6} {copied:>7} {skipped:>8}")
        total_copied += copied
        total_skipped += skipped
    print("-" * 60)
    print(f"{'TOTAL':<30} {'':>6} {total_copied:>7} {total_skipped:>8}")
    print("=" * 60)
    print("\nMigration complete. Cloud data is untouched.")

    await cloud.close()
    await local.close()


if __name__ == "__main__":
    asyncio.run(main())
