import logger from '@/lib/logger';
/**
 * TaskContentPreview - Content display section
 *
 * Displays:
 * - Task topic/title
 * - Generated content preview WITH MARKDOWN RENDERING
 * - Featured image
 * - Edit mode for all fields
 */

import React, { useState, useEffect } from 'react';
import DOMPurify from 'dompurify';
import PropTypes from 'prop-types';
import {
  Box,
  Button,
  TextField,
  Switch,
  FormControlLabel,
  Snackbar,
  Alert,
} from '@mui/material';
import { updateTaskContent } from '../../services/taskService';

const TaskContentPreview = ({ task, onTaskUpdate }) => {
  const [isEditing, setIsEditing] = useState(false);
  const [editedTitle, setEditedTitle] = useState('');
  const [editedContent, setEditedContent] = useState('');
  const [showPreview, setShowPreview] = useState(true);
  const [saving, setSaving] = useState(false);
  const [snackbar, setSnackbar] = useState({
    open: false,
    message: '',
    severity: 'success',
  });
  const handleSnackbarClose = () =>
    setSnackbar((prev) => ({ ...prev, open: false }));

  // Extract title from content if it starts with markdown title
  const extractTitleFromContent = (content) => {
    if (!content) return { title: null, cleanedContent: content };

    const match = content.match(/^#+\s+(.+?)(?:\n|$)/);
    if (match) {
      const title = match[1].trim();
      const cleanedContent = content.replace(/^#+\s+.+?(?:\n|$)/, '').trim();
      return { title, cleanedContent };
    }
    return { title: null, cleanedContent: content };
  };

  useEffect(() => {
    if (task) {
      // Check multiple possible locations for content (in priority order)
      // 1. task.result.draft_content (generated by LLM)
      // 2. task.result.content (published content)
      // 3. task.task_metadata.content (legacy location)
      const taskResult =
        typeof task.result === 'string'
          ? (() => {
              try {
                return JSON.parse(task.result);
              } catch (error) {
                logger.error('Failed to parse task result:', error);
                return {};
              }
            })()
          : task.result || {};

      const content =
        taskResult.draft_content ||
        taskResult.content ||
        task.task_metadata?.content ||
        '';

      const { title: extractedTitle, cleanedContent } =
        extractTitleFromContent(content);

      // Use extracted title if available, otherwise use topic
      setEditedTitle(extractedTitle || task.topic || '');
      setEditedContent(cleanedContent);
    }
  }, [task]);

  if (!task) return null;

  // Convert markdown to HTML with better header detection (handles underline-style headers)
  const renderMarkdown = (markdown) => {
    if (!markdown)
      return '<p style="color: #999; font-style: italic;">No content available</p>';

    let html = markdown
      // Headers with dashes/equals (underline style) - must come BEFORE regular markdown headers
      .replace(/^(.*?)\n={3,}\n/gm, '<h1>$1</h1>')
      .replace(/^(.*?)\n-{3,}\n/gm, '<h2>$1</h2>')
      // Regular markdown headers
      .replace(/^### (.*$)/gim, '<h3>$1</h3>')
      .replace(/^## (.*$)/gim, '<h2>$1</h2>')
      .replace(/^# (.*$)/gim, '<h1>$1</h1>')
      // Horizontal rules
      .replace(/^={3,}$/gm, '<hr/>')
      .replace(/^_{3,}$/gm, '<hr/>')
      // Bold and italic
      .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
      .replace(/__(.*?)__/g, '<strong>$1</strong>')
      .replace(/\*(.*?)\*/g, '<em>$1</em>')
      .replace(/_(.*?)_/g, '<em>$1</em>')
      // Links
      .replace(
        /\[(.*?)\]\((.*?)\)/g,
        '<a href="$2" style="color: #00d9ff; text-decoration: underline;">$1</a>'
      )
      // Lists
      .replace(/^\* (.*$)/gim, '<li>$1</li>')
      .replace(/^- (.*$)/gim, '<li>$1</li>')
      // Code blocks and inline code
      .replace(
        /```([\s\S]*?)```/g,
        '<pre style="background: #1a1a1a; padding: 12px; border-radius: 4px; overflow-x: auto;"><code>$1</code></pre>'
      )
      .replace(
        /`(.*?)`/g,
        '<code style="background: #1a1a1a; padding: 2px 6px; border-radius: 3px; font-family: monospace;">$1</code>'
      )
      // Line breaks and paragraphs
      .replace(/\n\n+/g, '</p><p>')
      .replace(/\n/g, '<br/>');

    // Wrap list items in <ul>
    html = html.replace(
      /(<li>.*?<\/li>)/s,
      '<ul style="margin-left: 24px;">$1</ul>'
    );
    // Fix improperly nested tags
    html = html
      .replace(/<p>\s*<(h[123]|pre|ul|ol|hr)/g, '<$1')
      .replace(/<\/(h[123]|pre|ul|ol|hr)>\s*<\/p>/g, '</$1>');

    return `<div style="line-height: 1.8; font-family: 'Segoe UI', Arial, sans-serif;"><p>${html}</p></div>`;
  };

  const handleSave = async () => {
    setSaving(true);
    try {
      const updatedTask = await updateTaskContent(task.id, {
        topic: editedTitle,
        task_metadata: {
          ...task.task_metadata,
          content: editedContent,
        },
      });
      setIsEditing(false);
      if (onTaskUpdate) onTaskUpdate(updatedTask);
      setSnackbar({
        open: true,
        message: 'Changes saved successfully',
        severity: 'success',
      });
    } catch (error) {
      logger.error('Failed to save changes:', error);
      setSnackbar({
        open: true,
        message: 'Failed to save changes',
        severity: 'error',
      });
    } finally {
      setSaving(false);
    }
  };

  return (
    <Box sx={{ display: 'flex', flexDirection: 'column', gap: 3 }}>
      {/* Content Title */}
      <Box sx={{ mb: 2 }}>
        {isEditing ? (
          <TextField
            fullWidth
            value={editedTitle}
            onChange={(e) => setEditedTitle(e.target.value)}
            label="Title"
            variant="outlined"
            sx={{
              '& .MuiOutlinedInput-root': {
                color: '#00d9ff',
                fontSize: '24px',
                fontWeight: 'bold',
              },
              '& .MuiInputLabel-root': { color: '#999' },
              '& .MuiOutlinedInput-notchedOutline': { borderColor: '#333' },
            }}
          />
        ) : (
          <>
            <h2
              style={{
                margin: '0 0 8px 0',
                color: '#00d9ff',
                fontSize: '24px',
              }}
            >
              {editedTitle || task.topic || 'Untitled'}
            </h2>
            <small style={{ color: '#999' }}>ID: {task.id}</small>
          </>
        )}
      </Box>

      {/* Edit Controls */}
      <Box sx={{ display: 'flex', gap: 2, alignItems: 'center' }}>
        {isEditing ? (
          <>
            <Button
              variant="contained"
              onClick={handleSave}
              disabled={saving}
              sx={{ backgroundColor: '#00d9ff', color: '#000' }}
            >
              {saving ? 'Saving...' : '💾 Save Changes'}
            </Button>
            <Button
              variant="outlined"
              onClick={() => {
                setIsEditing(false);
                setEditedTitle(task.topic || '');
                setEditedContent(task.task_metadata?.content || '');
              }}
              disabled={saving}
              sx={{ borderColor: '#999', color: '#999' }}
            >
              Cancel
            </Button>
          </>
        ) : (
          <Button
            variant="outlined"
            onClick={() => setIsEditing(true)}
            sx={{ borderColor: '#00d9ff', color: '#00d9ff' }}
          >
            ✏️ Edit Content
          </Button>
        )}
        {!isEditing && (
          <FormControlLabel
            control={
              <Switch
                checked={showPreview}
                onChange={(e) => setShowPreview(e.target.checked)}
                sx={{
                  '& .MuiSwitch-switchBase.Mui-checked': {
                    color: '#00d9ff',
                  },
                  '& .MuiSwitch-switchBase.Mui-checked + .MuiSwitch-track': {
                    backgroundColor: '#00d9ff',
                  },
                }}
              />
            }
            label="Preview Mode"
            sx={{ color: '#999' }}
          />
        )}
      </Box>

      {/* Content Preview/Editor */}
      <Box>
        <h3 style={{ marginTop: 0, color: '#e0e0e0' }}>
          📝 Content {showPreview && !isEditing ? 'Preview' : 'Editor'}
        </h3>
        {isEditing ? (
          <TextField
            fullWidth
            multiline
            rows={20}
            value={editedContent}
            onChange={(e) => setEditedContent(e.target.value)}
            placeholder="Write your content in Markdown..."
            variant="outlined"
            sx={{
              '& .MuiOutlinedInput-root': {
                color: '#e0e0e0',
                fontFamily: 'monospace',
                fontSize: '13px',
                backgroundColor: '#0f0f0f',
              },
              '& .MuiInputLabel-root': { color: '#999' },
              '& .MuiOutlinedInput-notchedOutline': { borderColor: '#333' },
            }}
          />
        ) : showPreview ? (
          <Box
            sx={{
              backgroundColor: '#0f0f0f',
              padding: 3,
              borderRadius: 1,
              maxHeight: '600px',
              overflowY: 'auto',
              border: '1px solid #333',
              fontSize: '16px',
              color: '#e0e0e0',
              '& h1': {
                fontSize: '32px',
                marginTop: '24px',
                marginBottom: '16px',
                color: '#00d9ff',
              },
              '& h2': {
                fontSize: '28px',
                marginTop: '20px',
                marginBottom: '12px',
                color: '#00d9ff',
              },
              '& h3': {
                fontSize: '24px',
                marginTop: '16px',
                marginBottom: '10px',
                color: '#00d9ff',
              },
              '& p': { marginBottom: '16px' },
              '& ul': { marginLeft: '24px', marginBottom: '16px' },
              '& li': { marginBottom: '8px' },
              '& strong': { fontWeight: 'bold', color: '#fff' },
              '& em': { fontStyle: 'italic' },
            }}
            dangerouslySetInnerHTML={{
              __html: DOMPurify.sanitize(renderMarkdown(editedContent)),
            }}
          />
        ) : (
          <Box
            sx={{
              backgroundColor: '#0f0f0f',
              padding: 2,
              borderRadius: 1,
              maxHeight: '500px',
              overflowY: 'auto',
              border: '1px solid #333',
              fontFamily: 'monospace',
              fontSize: '13px',
              lineHeight: '1.5',
              color: '#e0e0e0',
            }}
          >
            <pre
              style={{
                whiteSpace: 'pre-wrap',
                wordWrap: 'break-word',
                margin: 0,
              }}
            >
              {editedContent}
            </pre>
          </Box>
        )}
      </Box>

      {/* Featured Image */}
      {(task.task_metadata?.featured_image_url ||
        task.result?.featured_image_url) && (
        <Box>
          <h3 style={{ marginTop: 0, color: '#e0e0e0' }}>🖼️ Featured Image</h3>
          <Box
            component="img"
            src={
              task.task_metadata?.featured_image_url ||
              task.result?.featured_image_url
            }
            alt="Featured"
            sx={{
              maxWidth: '100%',
              maxHeight: '400px',
              borderRadius: 1,
              border: '1px solid #333',
              objectFit: 'contain',
            }}
          />
        </Box>
      )}

      {/* Toast notifications (replaces native alert() calls) */}
      <Snackbar
        open={snackbar.open}
        autoHideDuration={4000}
        onClose={handleSnackbarClose}
        anchorOrigin={{ vertical: 'bottom', horizontal: 'center' }}
      >
        <Alert
          onClose={handleSnackbarClose}
          severity={snackbar.severity}
          variant="filled"
          sx={{ width: '100%' }}
        >
          {snackbar.message}
        </Alert>
      </Snackbar>
    </Box>
  );
};

TaskContentPreview.propTypes = {
  task: PropTypes.shape({
    id: PropTypes.string.isRequired,
    topic: PropTypes.string,
    task_metadata: PropTypes.oneOfType([
      PropTypes.string,
      PropTypes.shape({
        content: PropTypes.string,
        featured_image_url: PropTypes.string,
      }),
    ]),
    result: PropTypes.oneOfType([
      PropTypes.string,
      PropTypes.shape({
        featured_image_url: PropTypes.string,
      }),
    ]),
  }),
  onTaskUpdate: PropTypes.func,
};

export default TaskContentPreview;
