"""
Migration 0032: Add index on writing_samples.user_id (architectural note for issue #316).

Issue #316 requested casting writing_samples.user_id (VARCHAR) to UUID and adding a FK
to users.id. However, investigation reveals a deeper architectural mismatch:

- writing_samples.user_id stores the GitHub OAuth numeric integer ID (e.g. "12345678")
  taken from JWT claims["user_id"], which comes from github_user["id"] — a plain integer.
- users.id is an internal UUID generated by str(uuid4()) at user-creation time.

These are different identity systems. The GitHub numeric ID cannot be cast to UUID, and
there is no FK relationship between the two columns that can be enforced at the DB level
without first unifying the identity model (i.e. storing the internal UUID in the JWT, or
adding a github_id column to users and indexing through it).

Until that architectural change is made, this migration:
1. Adds an index on writing_samples.user_id (if not already present) to ensure fast
   per-user lookup without requiring a type change.
2. Documents the identity-model gap so it is visible in schema_migrations history.

The type-cast and FK addition from the original issue are deferred to a future migration
that must also update the auth system to use internal UUIDs in JWT claims.

Rollback: drop the index added by this migration.
"""

from services.logger_config import get_logger

logger = get_logger(__name__)


async def up(pool) -> None:
    """Add index on writing_samples.user_id if not present."""
    async with pool.acquire() as conn:
        ws_exists = await conn.fetchval(
            "SELECT EXISTS(SELECT FROM information_schema.tables WHERE table_name = 'writing_samples')"
        )
        if not ws_exists:
            logger.warning("Table 'writing_samples' does not exist — skipping")
            return

        idx_exists = await conn.fetchval(
            "SELECT 1 FROM pg_indexes WHERE indexname = 'idx_writing_samples_user_id'"
        )
        if not idx_exists:
            await conn.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_writing_samples_user_id
                    ON writing_samples(user_id)
                """
            )
            logger.info("Created idx_writing_samples_user_id")
        else:
            logger.info("Index idx_writing_samples_user_id already exists — no action needed")

        logger.info(
            "NOTE (issue #316): writing_samples.user_id stores GitHub OAuth integer IDs, "
            "not internal UUID from users.id. FK addition deferred pending auth identity unification."
        )


async def down(pool) -> None:
    """Remove index added by this migration."""
    async with pool.acquire() as conn:
        await conn.execute("DROP INDEX IF EXISTS idx_writing_samples_user_id")
    logger.info("Removed idx_writing_samples_user_id (rollback of 0032)")
